参考
https://hibiki-press.tech/python/mecab/5153

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import MeCab
import pandas as pd
import numpy as np

In [5]:
keyword = 'あっぷる'
filename = '../'+keyword+ '.csv'

In [6]:
df = pd.read_csv(filename)
df.head()

keyword           site_name snnipet  \
0    あっぷる           Apple（日本）   キャッシュ   
1    あっぷる  iPhone - Apple（日本）   キャッシュ   
2    あっぷる    Apple Storeオンライン   キャッシュ   
3    あっぷる    iPad - Apple（日本）   キャッシュ   
4    あっぷる   Watch - Apple（日本）   キャッシュ   

                                              URL  ranking  
0         =HYPERLINK("https://www.apple.com/jp/")        1  
1  =HYPERLINK("https://www.apple.com/jp/iphone/")        2  
2    =HYPERLINK("https://www.apple.com/jp/store")        3  
3    =HYPERLINK("https://www.apple.com/jp/ipad/")        4  
4   =HYPERLINK("https://www.apple.com/jp/watch/")        5

https://www.delftstack.com/ja/howto/python-pandas/how-to-delete-dataframe-row-in-pandas-based-on-column-value/

In [7]:
cb1 = (df['snnipet'] == 'キャッシュ' )
cb2 = (df['snnipet'] == '類似ページ' )
condition_bool = (cb1 | cb2)
df.drop(df[ condition_bool == True ].index, inplace=True)
df

keyword                                       site_name  \
7     あっぷる                         Apple Music - Apple（日本）   
9     あっぷる                               Apple - Wikipedia   
15    あっぷる        アップル(Apple) - 【メルカリ】No.1フリマアプリ - Mercari   
16    あっぷる                    Appleに関する最新記事831件 | WIRED.jp   
20    あっぷる                        Apple Arcade - Apple（日本）   
29    あっぷる            アップル（読み）あっぷる（英語表記）Apple Inc. - コトバンク   
30    あっぷる                              あっぷる新着情報 - NBC長崎放送   
31    あっぷる            介護の応援団【あっぷる】 姫路市 - 加古川市 - たつの市 - 明石市   
36    あっぷる               あっぷる (@ririka0221apple) | Twitter   
37    あっぷる                            Apple（アップル） - 価格.com   
38    あっぷる                                     あっぷるぐりむグループ   
39    あっぷる                            アップルの一覧 | ギズモード・ジャパン   
41    あっぷる                              コンタクトレンズ通販 レンズアップル   
42    あっぷる                           Apple TV+ - Apple（日本）   
46    あっぷる                    アップル、「iOS 15」発表 - ケータイ Watch   
47    あっぷる                                  | 介護の応援団【あっぷる】   
48    あっぷる                   あっぷるタイムス最新号更新しました - アップルハウジング   
49    あっぷる                                アップル - Wikipedia   
50    あっぷる                       かふぇ あっぷる - 人形町/カフェ | 食べログ   
51    あっぷる     GRANNY SMITH APPLE PIE & COFFEE グラニースミス ...   
53    あっぷる                        iPhone SEを購入 - Apple（日本）   
57    あっぷる                                   坂城店 | 美容室あっぷる   
58    あっぷる              「アップルストア」の検索結果 - 【楽天市場】ジャンルトップ ...   
59    あっぷる                          車販売 - 中古車買取・中古車査定のアップル   
62    あっぷる                株式会社あっぷる ソーシャルメディアポリシー - 117グループ   
63    あっぷる                               秋田プレミアムあっぷる | TOP   
65    あっぷる                 Appleのスマートフォン・格安スマホ 最新人気機種ランキング   
66    あっぷる                   最新の apple ニュース - Engadget 日本版   
67    あっぷる        (株) あっぷる関西 尼崎南店｜ (兵庫県尼崎市) 中古車なら - グー ...   
68    あっぷる                                      アップル引越センター   
69    あっぷる                         APPLE｜マネキン トルソ 株式会社アップル   
70    あっぷる                          元気あっぷる体操 - 青森放送局 - NHK   
75    あっぷる                               秋田プレミアムあっぷる | TOP   
76    あっぷる                アップル【AAPL】：掲示板/株価 - Yahoo!ファイナンス   
77    あっぷる                         アップル引越センター | 公式サイトなら最安値   
78    あっぷる               株式会社アップル コーポレートサイト｜アパマンショップFC ...   
79    あっぷる                  英会話｜大阪・梅田と難波の英会話スクール【アップルk ...   
80    あっぷる         アップル四日市ときわ店 (三重県四日市) の詳細 - 中古車 - グー ...   
83    あっぷる                        店舗を探す - 中古車買取・中古車査定のアップル   
84    あっぷる                            中古車買取・中古車査定のアップル【公式】   
85    あっぷる                                   あっぷるワイド - NHK   
86    あっぷる             あっぷる関西 グループ公式 | 西日本最大級の国産車・輸入車の ...   
87    あっぷる                               個別教室のアップル ／宮城県仙台市   
88    あっぷる               Apple(アップル)のタブレットPC 製品一覧 - 価格.com   
89    あっぷる            アップルアンドローゼス: 【Apple&Roses】薔薇のタルト ...   
90    あっぷる                               アップルワールド旅行会社専用サイト   
91    あっぷる                        味処あっぷる亭 - 上伊田/居酒屋 | 食べログ   
92    あっぷる                       ‎「Apple Store」をApp Storeで   
93    あっぷる                      無料査定申込み - 中古車買取・中古車査定のアップル   
94    あっぷる    AAPL:NASDAQ GS 株価 - アップル - Bloomberg Markets   
95    あっぷる           ホットアップルパイ | メニュー情報 | McDonald's Japan   
96    あっぷる  アップル Apple Apple Pencil 第2世代 [MU8F2J/A] - ヨドバシ   
97    あっぷる   アップル Apple MK0C2J/A [Apple Pencil] 通販【全品無料配達】   
99    あっぷる                      津軽のお宿 南田温泉ホテルアップルランド【公式HP】   

                                              snnipet  \
7                        Apple Musicはどうすれば聴くことができますか？   
9   Apple Inc. （アップル）は、カリフォルニア州クパチーノに本社を置くアメリカ合衆国の...   
15  アップル - アップルはアメリカの企業で、日本においてもさまざまな製品やサービスが人気を集め...   
16  Apple（アップル）は、インターネット関連製品、デジタル家庭電化製品、ソフトウェア製品を開...   
20                          どのくらいのペースで新しいゲームが追加されますか？   
29  日本大百科全書(ニッポニカ) - アップルの用語解説 - アメリカのコンピュータ会社。本社所...   
30  あっぷる新着情報. 3/19（木）ささみと豆もやしの香草和え他. 礒永 由紀 先生 料理レシ...   
31           介護保険申請代行・ケアプラン作成・介護サービスなら117グループ「あっぷる」へ.   
36  The latest Tweets from あっぷる (@ririka0221apple)...   
37  Apple（アップル）の製品をカテゴ

In [8]:
def text_to_words(text):
    tagger = MeCab.Tagger("-O wakati")
    return tagger.parse(text).split()

In [9]:
texts = df['snnipet'].tolist()
texts
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

['Apple Musicはどうすれば聴くことができますか？',
 'Apple Inc. （アップル）は、カリフォルニア州クパチーノに本社を置くアメリカ合衆国の多国籍テクノロジー企業である。デジタル家庭電化製品、ソフトウェア、オンラインサービスの開発・販売を行っている。',
 'アップル - アップルはアメリカの企業で、日本においてもさまざまな製品やサービスが人気を集めています。デザイナーを中心に人気のあるMac、スマートフォンの認知度を広めたとも言えるiPhone、タブレット端末のiPadなどがあります。',
 'Apple（アップル）は、インターネット関連製品、デジタル家庭電化製品、ソフトウェア製品を開発・販売する多国籍企業。代表的なハードウェア製品として、スマートフォンのiPhone、タブレット型情報端末のiPad、パーソナルコンピュータのMacintosh、携帯\xa0...',
 'どのくらいのペースで新しいゲームが追加されますか？',
 '日本大百科全書(ニッポニカ) - アップルの用語解説 - アメリカのコンピュータ会社。本社所在地はカリフォルニア州クパーチーノ。カナダ産のリンゴであるマッキントッシュMacintoshに由来するリンゴのロゴマークで有名。2007年1月に社名を従来のアップル・\xa0...',
 'あっぷる新着情報. 3/19（木）ささみと豆もやしの香草和え他. 礒永 由紀 先生 料理レシピはこちら ... 出演者. NBCあっぷるtwitter. あっぷるfacebook. あっぷるテレPlus+. あっぷる. 番組でご紹介した情報 · 出演者の紹介 · あっぷるクッキング\xa0...',
 '介護保険申請代行・ケアプラン作成・介護サービスなら117グループ「あっぷる」へ.',
 'The latest Tweets from あっぷる (@ririka0221apple). PKAのA（@pka_123） サブ（@aptan_21）  あぽちゃんねる↪︎ https://t.co/P1Ecuu5iUq.',
 'Apple（アップル）の製品をカテゴリから探すことができます。カテゴリごとの人気売れ筋製品ランキングや、新着ニュースなど、Apple（アップル）の製品に関する情報はここでチェック！',
 '株式会社あっぷるアイビー. ［

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(385,) が単語数
(385,)
[ 28 121  68 127 203 315 366 368  40 218 334  56 311 323  31 348 347 247
 227 214]
28
apple 15
アップル 12
あっぷる 4
アップルの車買取 3
レビュー 3
無料で自動車の買取相場が分かります 3
車のことなら国内最大級の買取実績アップルへ 3
車査定サービス 3
ios 3
介護サービスなら117グループ 2
秋田あっぷるで秋田の情報を知る 2
pencil 2
温泉 2
画像も盛り沢山 2
com 2
英会話 2
翌日お届け実施中 2
即日 2
会社 2
今なら日本全国へ全品配達料金無料 2
介護保険申請代行 2
あっぷるぐりむグループ 2
inc 2
aapl 2
秋田美人 2
秋田県のタウン情報誌あっぷるが発信する秋田県の食べ処やラーメン 2
ケアプラン作成 2
元気あっぷる体操 2
デジタル家庭電化製品 2
ランキング 2
ご購入でゴールドポイント取得 2
の通販ならヨドバシカメラの公式サイト 2
ヨドバシ 2
お得なクーポンまで情報満載サイト 2
団体 2
販売開始 2
800 2
アップル発表イベント直前に 1
の公式企業サイトです 1
アップルは1人暮らし 1
アップルは8日 1
アップルはアメリカの企業で 1
アップルアンドローゼス 1
アップルストア 1
アップル引越センター 1
のホームページです 1
のタブレットpc製品一覧 1
の掲示板 1
アップルハウジングは 1
のスマートフォンをランキング形式でご紹介 1
のこと 1
の店舗情報は食べログでチェック 1
を発表した 1
の株価 1
の製品に関する情報はここでチェック 1
を立ち上げ 1
アップルの用語解説 1
の製品をカテゴリから探すことができます 1
の詳細な予想公開 1
アップルの中古車買取 1
は広大な津軽平野と岩木山を眺めるりんごづくしの温泉旅館です 1
アップルに関する記事一覧ページです 1
アップルkランゲージ 1
アップルapp 1
やきとり居酒屋きらび本店 1
りんごで作ったアップルタルトやアップルパイを販売しています 1
を開発しました 1
駅前の大人スクール 1
エンターテイメントの情報まで 1
アパート 1
アパートの仲介店舗を多

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(tokenizer=text_to_words, ngram_range=(1,2))
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(2736,) が単語数
(2736,)
[ 889  363   31  450 1090  757 1138 1520   33  854 2681 1012  977  638
 2044 1013  551  604  517  702]
889
の 118
、 105
. 93
。 74
を 47
で 47
アップル 43
・ 40
. . 40
に 38
！ 31
ます 30
は 29
が 28
情報 26
ます 。 26
あっぷる 24
お 23
」 23
し 22
「 22
車 20
て 18
や 18
も 18
apple 16
と 16
な 14
（ 14
） 14
1 13
など 12
なら 12
こと 12
た 12
ご 11
です 11
会社 11
買取 11
サービス 10
販売 10
秋田 10
です 。 9
し て 9
は 、 9
) 9
する 9
( 9
製品 9
県 8
· 8
/ 8
車 の 8
日本 8
無料 8
へ 8
でき 7
でき ます 7
介護 7
企業 6
まで 6
査定 6
株式 6
サイト 6
／ 6
の 買取 6
お 届け 6
- 6
届け 6
人気 6
店舗 5
年 5
中 5
など 、 5
青森 5
予約 5
実績 5
から 5
か 5
国内 5
し た 5
品 5
さ 5
ホテル 5
株式 会社 5
ランキング 5
車 買取 5
アップル は 5
アップル の 5
, 5
グループ 5
（ アップル 5
最大 5
！ ！ 5
こと が 5
2 5
者 5
a 5
の こと 5
レンズ 4
車 査定 4
無料 で 4
の 製品 4
ヨドバシ 4
の 情報 4
査定 サービス 4
ある 4
こと なら 4
し ます 4
県 の 4
相場 が 4
相場 4
秋田 県 4
て い 4
て いる 4
分かり ます 4
分かり 4
で ご 4
級 4
級 の 4
で 自動 4
い 4
が 分かり 4
が でき 4
価格 4
得 4
か ？ 4
自動 4
自動 車 4
製 4
製 品 4
: 4
いる 4
い ます 4
温泉 4
買取 ・ 4
スマート フォン 4
日 4
フォン 4
？ 4
スマート 4
開発 4
最新 4
アメリカ 4
. あっぷる 4
限定 4
、 お 4
月 4
サービス 。 4
情報 、 4


In [16]:
texts = df['snnipet']
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

https://qiita.com/chamao/items/7edaba62b120a660657e
これみたら最強．ほぼこれ+max_dfの設定

In [17]:
import MeCab
def wakati(text):
    tagger = MeCab.Tagger('')
    tagger.parse('') 
    node = tagger.parseToNode(text)
    word_list = []
    while node:
        pos = node.feature.split(",")[0]
        if pos in ["名詞", "動詞", "形容詞"]:   # 対象とする品詞
            word = node.surface
            word_list.append(word)
        node = node.next
    return " ".join(word_list)

#例
# text = 'どれだけの天才でもどれだけの馬鹿でも自分一人だけの純粋な世界なんて存在しえないんだ。'
# print(wakati(text))  #=> どれ 天才 どれ 馬鹿 自分 一 人 純粋 世界 存在 し え ん

df["target"] = df['snnipet'].apply(wakati)

In [18]:
df["target"]

7                               Apple Music すれ 聴く こと でき
9     Apple Inc アップル カリフォルニア 州 クパチーノ 本社 置く アメリカ 合衆 国...
15    アップル アップル アメリカ 企業 日本 おい 製品 サービス 人気 集め い デザイナー ...
16    Apple アップル インターネット 関連 デジタル 家庭 電化 ソフトウェア 製品 開発 ...
20                                     ペース 新しい ゲーム 追加 さ
29    日本 百科 全書 ニッポニカ アップル 用語 解説 アメリカ コンピュータ 会社 本社 所在...
30    あっぷる 新着 情報 3 19 木 ささみ 豆もやし 香草 他 礒 永 由紀 先生 料理 レ...
31          介護 保険 申請 代行 ケア プラン 作成 介護 サービス 117 グループ あっぷる
36    The latest Tweets from あっぷる ririka 0221 apple ...
37    Apple アップル 製品 カテゴリ 探す こと でき カテゴリ 人気 売れ筋 製品 ランキ...
38    株式 会社 あっぷる アイビー グループ イタリアン レストラン ピッツェリア 焼肉 バーン...
39    アップル 関する 記事 一覧 ページ GIZMODO JAPAN 最新 フォン デジタル デ...
41    コンタクト レンズ 通販 レンズ アップル 安心 便利 コンタクト レンズ オン ライン シ...
42                                          すれ 観る こと でき
46    アップル 8 日本 時間 開発 イベント WWDC 21 iOS 15 発表 し 今秋 提供...
47    介護 保険 申請 代行 ケア プラン 作成 介護 サービス 117 グループ あっぷる 問い...
48    アップル ハウジング 福岡 新築 住宅 リフォーム マンション リフォーム 通し 人 環境 ...
49    アップル apple 英語 リンゴ 林檎 こと 目次 1 会社 団体 1 1 架空 

In [126]:
import mojimoji
df["target"] = df["target"].apply(mojimoji.zen_to_han)
df["target"]

0     WEAR ｳｪｱ 日本 最大 ﾌｧｯｼｮﾝ ｺｰﾃﾞｨﾈｰﾄ ｻｲﾄ ﾓﾃﾞﾙ 俳優 ｼｮｯ...
1                                                 ｷｬｯｼｭ
2     ﾌｧｯｼｮﾝ 英 fashion 英語 発音 fæ n ﾌｧｼｬﾝ 仏 mode ﾌﾗﾝｽ ...
3     人気 ｷｭﾚｰｼｮﾝﾒﾃﾞｨｱ 最新 ﾌｧｯｼｮﾝ 情報 ﾚﾃﾞｨｰｽ 集め 話題 ﾌｧｯｼ...
4     ZOZOTOWN 8441 ﾌﾞﾗﾝﾄﾞ ｱｲﾃﾑ 公式 取扱う ﾌｧｯｼｮﾝ 通販 ｻｲﾄ...
                            ...                        
93    ﾌｧｯｼｮﾝ 通販 haco ﾊｺ 毎日 明日 昨日 びっくり できる 洋服 雑貨 ﾌﾟﾛｼ...
94    ﾌｧｯｼｮﾝ VOGUE JAPAN 公式 ｻｲﾄ 世界 ﾌｧｯｼｮﾝ ｺﾚｸｼｮﾝ はじめ...
95           Amazon 9 月 13 月 23 59 ﾌｧｯｼｮﾝ ﾀｲﾑ ｾｰﾙ 祭り 開催
96    Amazon ﾌｧｯｼｮﾝ ﾀｲﾑ ｾｰﾙ 祭り Amazon 開催 する 63 時間 ｾｰ...
97    ﾚﾃﾞｨｰｽ ﾌｧｯｼｮﾝ 通販 Re EDIT ﾘｴﾃﾞｨ ﾌｧｯｼｮﾝ 通販 ｻｲﾄ 強...
Name: target, Length: 98, dtype: object

In [127]:
def normalize_number(text):
    # 連続した数字を0で置換
    replaced_text = re.sub(r'\d+', '0', text)
    return replaced_text

In [130]:
df["target"] = df["target"].apply(normalize_number)
df["target"].head()

0    WEAR ｳｪｱ 日本 最大 ﾌｧｯｼｮﾝ ｺｰﾃﾞｨﾈｰﾄ ｻｲﾄ ﾓﾃﾞﾙ 俳優 ｼｮｯ...
1                                                ｷｬｯｼｭ
2    ﾌｧｯｼｮﾝ 英 fashion 英語 発音 fæ n ﾌｧｼｬﾝ 仏 mode ﾌﾗﾝｽ ...
3    人気 ｷｭﾚｰｼｮﾝﾒﾃﾞｨｱ 最新 ﾌｧｯｼｮﾝ 情報 ﾚﾃﾞｨｰｽ 集め 話題 ﾌｧｯｼ...
4    ZOZOTOWN 0 ﾌﾞﾗﾝﾄﾞ ｱｲﾃﾑ 公式 取扱う ﾌｧｯｼｮﾝ 通販 ｻｲﾄ ﾂｹ...
Name: target, dtype: object

In [132]:
import os
import urllib.request
def download_stopwords(path):
    url = 'http://svn.sourceforge.jp/svnroot/slothlib/CSharp/Version1/SlothLib/NLP/Filter/StopWord/word/Japanese.txt'
    if os.path.exists(path):
        print('File already exists.')
    else:
        print('Downloading...')
        # Download the file from `url` and save it locally under `file_name`:
        urllib.request.urlretrieve(url, path)
        
def create_stopwords(file_path):
    stop_words = []
    for w in open(path, "r"):
        w = w.replace('\n','')
        if len(w) > 0:
          stop_words.append(w)
    return stop_words    
        
path = "stop_words.txt"
download_stopwords(path)
stop_words = create_stopwords(path)
print(stop_words)

Downloading...


In [143]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b')
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
feature_sparse
features

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 1, 0, ..., 0, 0, 0],
       [1, 2, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]])

In [145]:
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(672,) が単語数
(672,)
[600   0 397 511 438 610 664 137  98 314 170 202 508 394  83 339 286 572
 386  24]
600
ﾌｧｯｼｮﾝ 153
0 68
通販 52
ｻｲﾄ 41
ｱｲﾃﾑ 41
ﾌﾞﾗﾝﾄﾞ 36
ﾚﾃﾞｨｰｽ 33
人気 33
し 32
無料 24
公式 18
商品 18
ｺﾚｸｼｮﾝ 17
送料 16
い 16
紹介 14
最新 13
ﾄﾚﾝﾄﾞ 12
購入 12
fashion 12
新作 11
ｱｳﾀｰ 11
する 11
代 11
楽天 11
価格 11
ﾜﾝ 11
ﾒﾝｽﾞ 11
情報 11
ｼｮｯﾌﾟ 10
買い物 10
取り扱う 10
開催 9
rakuten 9
取り揃え 9
入荷 8
ｻｲｽﾞ 8
ｾｰﾙ 8
ﾆｭｰｽ 8
得 7
女性 7
ｽｶｰﾄ 7
ﾄｯﾌﾟｽ 7
ﾊﾞｯｸﾞ 7
ﾊﾟﾝﾂ 7
ﾋﾟｰｽ 7
ｼｭｰｽﾞ 7
税込 7
ﾍﾟｰｼﾞ 7
ｼｮｯﾋﾟﾝｸﾞ 6
いただけ 6
品揃え 6
流行 6
掲載 6
ﾁｪｯｸ 6
amazon 6
ｼﾞｬｹｯﾄ 6
おしゃれ 6
ｱﾍﾞﾆｭｰ 5
ｳｪｱ 5
ﾈｯﾄ 5
ｸｰﾎﾟﾝ 5
できる 5
ｶｼﾞｭｱﾙ 5
ｶﾃｺﾞﾘ 5
ｷｬｯｼｭ 5
洋服 5
ｱｰﾄ 5
ﾗﾝｷﾝｸﾞ 5
いる 5
手数 5
大人 5
小物 5
旧 5
ｺｰﾃﾞ 5
ﾗｲﾌｽﾀｲﾙ 5
多数 5
中心 4
ｲﾝ 4
以外 4
返品 4
配信 4
配送 4
最大 4
世界 4
ﾌﾟﾚｽ 4
一部 4
でき 4
ﾗｲﾝ 4
幅広く 4
ﾃﾞｨﾉｽ 4
販売 4
ｺｰﾃﾞｨﾈｰﾄ 4
ｽｰﾂ 4
ｵｰﾙ 4
ｵﾝ 4
ﾌﾟﾁﾌﾟﾗ 4
ｺｰﾄ 4
秋冬 4
あり 4
ｽﾅｯﾌﾟ 4
登場 4
ﾋﾞｭｰﾃｨ 4
取扱う 4
ｻｰﾋﾞｽ 3
ｷｯｽﾞ 3
zozotown 3
ｵｰｸｼｮﾝ 3
ｱｸｾｻﾘｰ 3
ｱﾏｿﾞﾝ 3
ご覧 3
ｲﾍﾞﾝﾄ 3
ｲﾝﾅｰ 3
ﾚﾎﾟｰﾄ 3
ｺｽﾒ 3
まとめ 3
ｱｳﾄﾚｯﾄ 3
百貨 3
店舗 3
届け 3
定番 3
安値 3
提供 3
安く 3
新品 3
日本 3
旬 3
最短 3
圧倒 3
ﾔﾌｵｸ 3
海外 3
古着 3
即日 3
類似 3
ﾓﾃﾞﾙ 3
素材 3


In [148]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(norm='l2', sublinear_tf=True)
tfidf = tfidf_transformer.fit_transform(feature_sparse)
tfidf

<98x672 sparse matrix of type '<class 'numpy.float64'>'
	with 1745 stored elements in Compressed Sparse Row format>

In [149]:
features = np.array(tfidf.todense())
feature_sparse
features
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(672,) が単語数
(672,)
[600   0 397 438 483 610 511 137 664  98 314 508 170 394 202 339  83 247
 270 297]
600
ﾌｧｯｼｮﾝ 8.348431451710944
0 5.989116859913201
通販 5.480465662904854
ｱｲﾃﾑ 5.001266559625482
ｷｬｯｼｭ 5.0
ﾌﾞﾗﾝﾄﾞ 4.993802492023004
ｻｲﾄ 4.936577817333788
人気 4.6712626787439016
ﾚﾃﾞｨｰｽ 4.241203982018595
し 4.024761909642024
無料 3.5426151255142653
ｺﾚｸｼｮﾝ 3.0196927021010085
公式 2.879353478678999
送料 2.7685444271031825
商品 2.766010304298127
紹介 2.669684892967058
い 2.630071151654917
情報 2.479275173023307
新作 2.3466599900691576
楽天 2.343134602350031
fashion 2.3374431627341146
ﾍﾟｰｼﾞ 2.3121685976023354
最新 2.2913439889203553
ﾒﾝｽﾞ 2.2497770304808236
取り扱う 2.249248410928829
ﾄﾚﾝﾄﾞ 2.159453149674609
rakuten 2.0999437820050195
買い物 2.0816003492289648
購入 1.9965552950486918
ｱｳﾀｰ 1.980988464327639
開催 1.9803970513639755
価格 1.929715128285037
入荷 1.9203549912879558
ｼｮｯﾌﾟ 1.864263634854858
代 1.854086198647504
類似 1.7673727935326942
する 1.761267644913004
ﾜﾝ 1.7533956208840145
税込 1.6954975642304304
おしゃれ 1.6579625859419576
取り揃え

In [151]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b', max_df=50, min_df=3)
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(145,) が単語数
(145,)
[  0  78  86 109 132 142  20  12  63  33  25 107  77   7  67  57  75 122
   2  23]
0
0 68
通販 52
ｱｲﾃﾑ 41
ｻｲﾄ 41
ﾌﾞﾗﾝﾄﾞ 36
ﾚﾃﾞｨｰｽ 33
人気 33
し 32
無料 24
商品 18
公式 18
ｺﾚｸｼｮﾝ 17
送料 16
い 16
紹介 14
最新 13
購入 12
ﾄﾚﾝﾄﾞ 12
fashion 12
価格 11
代 11
新作 11
楽天 11
する 11
ｱｳﾀｰ 11
情報 11
ﾜﾝ 11
ﾒﾝｽﾞ 11
取り扱う 10
ｼｮｯﾌﾟ 10
買い物 10
rakuten 9
取り揃え 9
開催 9
ﾆｭｰｽ 8
ｻｲｽﾞ 8
ｾｰﾙ 8
入荷 8
ﾄｯﾌﾟｽ 7
ﾊﾞｯｸﾞ 7
税込 7
ﾊﾟﾝﾂ 7
ｽｶｰﾄ 7
ﾋﾟｰｽ 7
ﾍﾟｰｼﾞ 7
ｼｭｰｽﾞ 7
得 7
女性 7
流行 6
いただけ 6
掲載 6
おしゃれ 6
ﾁｪｯｸ 6
品揃え 6
ｼｮｯﾋﾟﾝｸﾞ 6
amazon 6
ｼﾞｬｹｯﾄ 6
ﾈｯﾄ 5
ｸｰﾎﾟﾝ 5
ｱﾍﾞﾆｭｰ 5
ｷｬｯｼｭ 5
ｶﾃｺﾞﾘ 5
ｶｼﾞｭｱﾙ 5
旧 5
できる 5
ﾗﾝｷﾝｸﾞ 5
手数 5
ｺｰﾃﾞ 5
洋服 5
ﾗｲﾌｽﾀｲﾙ 5
小物 5
ｳｪｱ 5
いる 5
ｱｰﾄ 5
大人 5
多数 5
幅広く 4
ｽﾅｯﾌﾟ 4
ｺｰﾄ 4
取扱う 4
以外 4
ｺｰﾃﾞｨﾈｰﾄ 4
最大 4
ｽｰﾂ 4
ﾌﾟﾚｽ 4
ﾗｲﾝ 4
返品 4
ｵﾝ 4
あり 4
ｲﾝ 4
配送 4
配信 4
ｵｰﾙ 4
ﾋﾞｭｰﾃｨ 4
ﾌﾟﾁﾌﾟﾗ 4
中心 4
販売 4
でき 4
一部 4
秋冬 4
登場 4
ﾔﾌｵｸ 3
出品 3
まとめ 3
即日 3
ﾎﾞﾄﾑｽ 3
tv 3
ご覧 3
古着 3
zozotown 3
交換 3
最短 3
圧倒 3
落札 3
ｼﾞｭｴﾘｰ 3
ｺｽﾒ 3
ｷｯｽﾞ 3
ｵｰｸｼｮﾝ 3
ｲﾝﾅｰ 3
ｲﾍﾞﾝﾄ 3
ｱﾏｿﾞﾝ 3
ｱｳﾄﾚｯﾄ 3
類似 3
雑貨 3
除く 3
ﾄﾞﾚｽ 3
ﾚﾎﾟｰﾄ 3
訳あり 3
翌日 3
安く 3
美容 3
海外 3
ｽｳｪｯﾄ 3
旬 3
日本 3
新品 3
ﾌｧｽﾄ 3


In [158]:
np.sum(features,axis=1)

array([10,  1,  7, 16, 21, 10, 15, 20, 11, 17,  2,  1, 12, 13, 14, 14, 15,
       12, 14, 15,  1, 24, 15, 24, 16, 15,  7, 16, 13, 18,  1, 15, 19,  7,
       12, 22, 11,  6,  7,  3,  7, 12,  7,  1, 18,  8, 15, 15, 12,  1, 11,
        4,  7,  6, 10, 15, 15, 14, 22, 19, 18, 22, 14, 22, 13,  7,  7,  5,
        7, 15, 22, 22, 14, 22, 17, 15,  7, 10, 15,  8,  2, 14,  6,  6,  7,
        8,  4, 10,  1, 18,  4,  9,  9,  4, 11,  7, 17, 17])

どの文章も何かしらの特徴量はもっている．

In [161]:
print(features[1,:])
print(np.argmax(features[1,:]))
print(cv.get_feature_names()[np.argmax(features[1,:])])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
100
ｷｬｯｼｭ


In [162]:
np.sum(features,axis=0)[100]

5

In [186]:
cv.get_feature_names()

['0',
 'amazon',
 'fashion',
 'rakuten',
 'tv',
 'zozotown',
 'あり',
 'い',
 'いただけ',
 'いる',
 'おしゃれ',
 'ご覧',
 'し',
 'する',
 'でき',
 'できる',
 'まとめ',
 '一部',
 '中心',
 '交換',
 '人気',
 '代',
 '以外',
 '価格',
 '入荷',
 '公式',
 '出品',
 '即日',
 '取り扱う',
 '取り揃え',
 '取扱う',
 '古着',
 '品揃え',
 '商品',
 '圧倒',
 '多数',
 '大人',
 '女性',
 '安く',
 '安値',
 '定番',
 '小物',
 '届け',
 '幅広い',
 '幅広く',
 '店舗',
 '得',
 '情報',
 '手数',
 '掲載',
 '提供',
 '新作',
 '新品',
 '日本',
 '旧',
 '旬',
 '最大',
 '最新',
 '最短',
 '楽天',
 '洋服',
 '流行',
 '海外',
 '無料',
 '登場',
 '秋冬',
 '税込',
 '紹介',
 '美容',
 '翌日',
 '落札',
 '訳あり',
 '財布',
 '販売',
 '買い物',
 '購入',
 '返品',
 '送料',
 '通販',
 '配信',
 '配送',
 '開催',
 '除く',
 '雑貨',
 '類似',
 'ｱｰﾄ',
 'ｱｲﾃﾑ',
 'ｱｳﾀｰ',
 'ｱｳﾄﾚｯﾄ',
 'ｱﾍﾞﾆｭｰ',
 'ｱﾏｿﾞﾝ',
 'ｲﾍﾞﾝﾄ',
 'ｲﾝ',
 'ｲﾝﾅｰ',
 'ｳｪｱ',
 'ｵｰｸｼｮﾝ',
 'ｵｰﾙ',
 'ｵﾝ',
 'ｶｼﾞｭｱﾙ',
 'ｶﾃｺﾞﾘ',
 'ｷｬｯｼｭ',
 'ｷｯｽﾞ',
 'ｸｰﾎﾟﾝ',
 'ｺｰﾃﾞ',
 'ｺｰﾃﾞｨﾈｰﾄ',
 'ｺｰﾄ',
 'ｺｽﾒ',
 'ｺﾚｸｼｮﾝ',
 'ｻｲｽﾞ',
 'ｻｲﾄ',
 'ｼｭｰｽﾞ',
 'ｼｮｯﾋﾟﾝｸﾞ',
 'ｼｮｯﾌﾟ',
 'ｼﾞｬｹｯﾄ',
 'ｼﾞｭｴﾘｰ',
 'ｽｰﾂ',
 'ｽｳｪｯﾄ',
 'ｽｶｰﾄ',
 'ｽﾅｯﾌﾟ',
 'ｾｰﾙ',
 'ﾁｪｯｸ',
 'ﾄｯﾌﾟｽ',
 'ﾄﾚﾝﾄﾞ',
 'ﾄﾞﾚｽ',
 'ﾆｭ

In [187]:
df.site_name

0                    WEAR: ファッションコーディネート
2                     ファッション - Wikipedia
3            ファッションまとめ（レディース） - ZOZOTOWN
4                       ファッション通販ZOZOTOWN
5           ファッション通販SHOPLIST（ショップリスト ...
                     ...                
93    ファッション通販のhaco! | ハコ！毎日のお洋服と明日の ...
94              Fashion - ファッション - VOGUE
95     Amazonファッションタイムセール祭りでビジネスバッグが ...
96          Amazon ファッションタイムセール祭り - アマゾン
97            レディースファッション通販 Re:EDIT‐リエディ
Name: site_name, Length: 91, dtype: object