参考
https://hibiki-press.tech/python/mecab/5153

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
import MeCab
import pandas as pd
import numpy as np

In [6]:
filename = 'ファッション'+ '.csv'

In [166]:
df = pd.read_csv(filename)
df.head()

keyword                    site_name  \
0  ファッション          WEAR: ファッションコーディネート   
1  ファッション      人気のファッションコーディネート - WEAR   
2  ファッション           ファッション - Wikipedia   
3  ファッション  ファッションまとめ（レディース） - ZOZOTOWN   
4  ファッション             ファッション通販ZOZOTOWN   

                                             snnipet  \
0  WEAR（ウェア）は日本最大級のファッションコーディネートサイトです。モデルや俳優、ショップ...   
1                                              キャッシュ   
2  ファッション（英: fashion、英語発音: [ˈfæʃən] ファシャン。仏: mode...   
3  人気キュレーションメディアの最新ファッション情報（レディース）を集めました！今話題のファッシ...   
4  ZOZOTOWNは8441ブランドのアイテムを公式に取扱うファッション通販サイトです。「ツケ...   

                                                 URL  ranking  
0                     =HYPERLINK("https://wear.jp/")        0  
1          =HYPERLINK("https://wear.jp/coordinate/")        1  
2  =HYPERLINK("https://ja.wikipedia.org/wiki/%E3%...        2  
3  =HYPERLINK("https://zozo.jp/fashionnews/?sex=w...        3  
4                     =HYPERLINK("https://zozo.jp/")        4

https://www.delftstack.com/ja/howto/python-pandas/how-to-delete-dataframe-row-in-pandas-based-on-column-value/

In [185]:
cb1 = (df['snnipet'] == 'キャッシュ' )
cb2 = (df['snnipet'] == '類似ページ' )
condition_bool = (cb1 | cb2)
df.drop(df[ condition_bool == True ].index, inplace=True)
df

keyword                           site_name  \
0   ファッション                 WEAR: ファッションコーディネート   
2   ファッション                  ファッション - Wikipedia   
3   ファッション         ファッションまとめ（レディース） - ZOZOTOWN   
4   ファッション                    ファッション通販ZOZOTOWN   
5   ファッション        ファッション通販SHOPLIST（ショップリスト ...   
..     ...                                 ...   
93  ファッション  ファッション通販のhaco! | ハコ！毎日のお洋服と明日の ...   
94  ファッション            Fashion - ファッション - VOGUE   
95  ファッション   Amazonファッションタイムセール祭りでビジネスバッグが ...   
96  ファッション        Amazon ファッションタイムセール祭り - アマゾン   
97  ファッション          レディースファッション通販 Re:EDIT‐リエディ   

                                              snnipet  \
0   WEAR（ウェア）は日本最大級のファッションコーディネートサイトです。モデルや俳優、ショップ...   
2   ファッション（英: fashion、英語発音: [ˈfæʃən] ファシャン。仏: mode...   
3   人気キュレーションメディアの最新ファッション情報（レディース）を集めました！今話題のファッシ...   
4   ZOZOTOWNは8441ブランドのアイテムを公式に取扱うファッション通販サイトです。「ツケ...   
5   ファッション通販SHOPLIST（ショップリスト） レディースからメンズ・キッズまで、多様な...   
..                                                ...   
93  ファッション通販のhaco!（ハコ）は、わたしたちの毎日が、そして明日が、昨日よりちょっとび...   
94  ファッション誌『VOGUE JAPAN』の公式サイト。世界のファッションやコレクションをはじ...   
95        Amazonは9月13日（月）23:59までファッションタイムセール祭りを開催中です。   
96  Amazonファッションタイムセール祭りとはAmazonが開催する計63時間のビッグセール。...   
97  レディースファッション通販 Re:EDIT‐リエディのファッション通販サイト。強く、気品高く...   

                                                  URL  ranking  
0                      =HYPERLINK("https://wear.jp/")        0  
2   =HYPERLINK("https://ja.wikipedia.org/wiki/%E3%...        2  
3   =HYPERLINK("https://zozo.jp/fashionnews/?sex=w...        3  
4                      =HYPERLINK("https://zozo.jp/")        4  
5                =HYPERLINK("https://shop-list.com/")        5  
..                                                ...      ...  
93                 =HYPERLINK("https://www.haco.jp/")       93  
94      =HYPERLINK("https://www.vogue.co.jp/fashion")       94  
95  =HYPERLINK("https://japanese.engadget.com/amaz...       95  
96  =HYPERLINK("https://www.amazon.co.jp/b?ie=UTF8...       96  
97                   =HYPERLINK("https://reedit.jp/")       97  

[91 rows x 5 columns]

In [9]:
def text_to_words(text):
    tagger = MeCab.Tagger("-O wakati")
    return tagger.parse(text).split()

In [167]:
texts = df['snnipet'].tolist()
texts
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

['WEAR（ウェア）は日本最大級のファッションコーディネートサイトです。モデルや俳優、ショップスタッフの着こなし1000万枚以上の中からコーデを探せます。気にいったアイテムはそのまま購入も！',
 'キャッシュ',
 'ファッション（英: fashion、英語発音: [ˈfæʃən] ファシャン。仏: mode、フランス語発音: [mɔd] モッド）とは、ある時点において広く行われているスタイルや風習のことである。特に、人々の間で流行している服装を指すが、装いに関係する装身具、美容（\xa0...',
 '人気キュレーションメディアの最新ファッション情報（レディース）を集めました！今話題のファッションやトレンド情報をご覧いただけます。ZOZOTOWNは8444ブランドのアイテムを公式に取扱うファッション通販サイトです。',
 'ZOZOTOWNは8441ブランドのアイテムを公式に取扱うファッション通販サイトです。「ツケ払い」ならお支払は2ヶ月後！即日配送（一部地域）で最短翌日お届け。今なら割引クーポンを対象ショップ限定でご利用いただけます。秋冬アイテムぞくぞく入荷！',
 'ファッション通販SHOPLIST（ショップリスト） レディースからメンズ・キッズまで、多様なジャンルのファストファッションアイテムがまとめて買えるショッピングサイト。',
 '人気ブランドのアイテムが続々入荷中!!ファッションウォーカーは2200以上の人気ブランドを公式に取り扱うファッション通販サイトです。即日出荷・サイズ交換・返品可.',
 '【5000円（税込）以上送料無料】レディースファッションの通販ならベルメゾン。人気のレディースファッションを豊富に取り揃え。ベルメゾンのレディースファッションはおしゃれでサイズ多数！コート、ワンピース、パンツ、スカート、セール商品など品\xa0...',
 '流行のアイテムが何でも手に入る日本最大級のファストファッション通販サイト。GRL グレイルはレディースファッション洋服通販サイトです。',
 'ファッションプレスは、最新ファッションニュースや新作コレクション、ファッションショーのレポート等をスピーディに配信[2ページ目]。ファッション以外にもライフスタイルやビューティ、アート等のニュースも掲載しています。',
 '類似ページ',
 'キャッシュ'

In [96]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [111]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(580,) が単語数
(580,)
[288  70  47 280 387 159 259 278 527 232 225 418 114 219  17 200 149 475
 480 160]
288
ファッション 17
rakuten 9
fashion 8
パンツ 7
ワンピース 7
アウター 6
トップス 6
バッグ 6
税込 6
スカート 6
ジャケット 5
以上のお買い物で送料無料 5
さん 5
シューズ 5
3980円 5
キャッシュ 5
は人気ブランドを取り扱うファッション通販サイトです 5
新作アイテムも続々入荷中 5
旧楽天ブランドアベニュー 5
アウターコレクション開催中 4
レディースファッション 4
オールインワン 4
コート 4
アウトレット品 3
buyma 3
インナー 3
一部を除く 3
財布 3
ボトムス 3
アート 3
古着 3
30代 3
楽天ファッション 3
スウェット 3
送料無料 3
ファッション小物 3
かのん 3
全て 2
の公式通販サイト 2
手数料無料の商品もあります 2
zozotownは8444ブランドのアイテムを公式に取扱うファッション通販サイトです 2
帽子 2
小物 2
おしゃれなファッション洋服通販サイトdholic 2
人気ブランドのアイテムが続々入荷中 2
から 2
即日出荷 2
こと生見愛瑠 2
今回 2
今話題のファッションやトレンド情報をご覧いただけます 2
今週のファッションチェック 2
大きいサイズ 2
めるる 2
める 2
ぬくみ 2
不用品の処分には出品 2
ファッション通販shoplist 2
ディノスなら代引手数料無料 2
ディノス 2
チュニック 2
セットアップ 2
スーツ 2
ファッションウォーカーは2200以上の人気ブランドを公式に取り扱うファッション通販サイトです 2
ファッションショーのレポート等をスピーディに配信 2
ジャージ 2
ショップリスト 2
ファッションプレスは 2
ファッション以外にもライフスタイルやビューティ 2
シャツ 2
下着 2
サイズ交換 2
フォーマル 2
コスメ 2
カジュアル 2
メンズ 2
メンズからレディースまで品揃え豊富 2
メンズファッション 2
アート等のニュースも掲載しています 2
レディース 2
アクセサリー 2
三

In [112]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(tokenizer=text_to_words, ngram_range=(1,2))
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [113]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(3307,) が単語数
(3307,)
[ 409 1096 1889  551   49 1337  923 1061 1173 3127 3236 2148   50 1398
 1612 1279  988  905 1221  715]
409
、 199
の 165
ファッション 153
。 146
. 115
を 99
で 65
に 55
は 54
通販 52
！ 50
・ 44
. . 42
アイテム 41
サイト 41
や 40
な 40
て 39
ます 38
お 38
も 37
） 36
ブランド 36
ます 。 35
です 35
（ 34
レディース 33
; 33
人気 33
通販 サイト 33
です 。 32
し 32
ファッション 通販 30
が 29
など 25
無料 24
から 22
( 22
の ファッション 21
レディース ファッション 21
サイト です 20
品 20
) 20
なら 19
公式 18
さん 18
商品 18
· 18
人気 ブランド 17
し て 17
コレクション 17
アイテム を 17
て い 16
中 16
い ます 16
い 16
送料 16
送料 無料 16
「 15
まで 14
は 、 14
紹介 14
た 13
」 13
最新 13
以上 13
豊富 13
円 12
トレンド 12
fashion 12
購入 12
する 11
情報 11
ブランド の 11
中 ！ 11
新作 11
代 11
さん 、 11
メンズ 11
ご 11
ワン 11
価格 11
楽天 11
アウター 11
、 ファッション 11
ファッション を 11
ファッション の 10
人気 の 10
/ 10
月 10
の お 10
】 10
【 10
ショップ 10
の レディース 10
買い物 10
お 買い物 10
取り扱う 10
開催 9
ブランド を 9
サイト 。 9
ファッション アイテム 9
の アイテム 9
など 、 9
! 9
rakuten 9
rakuten fashion 9
取り揃え 9
セール 8
取り扱う ファッション 8
日 8
で 送料 8
入荷 8
ニュース 8
と 8
の 商品 8
公式 に 8
以上 の 8
サイズ 8
商品 を 8
アイテム が 8
を 公式 8
パンツ 7
フ

In [ ]:
texts = df['snnipet']
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

https://qiita.com/chamao/items/7edaba62b120a660657e
これみたら最強．ほぼこれ+max_dfの設定

In [121]:
import MeCab
def wakati(text):
    tagger = MeCab.Tagger('')
    tagger.parse('') 
    node = tagger.parseToNode(text)
    word_list = []
    while node:
        pos = node.feature.split(",")[0]
        if pos in ["名詞", "動詞", "形容詞"]:   # 対象とする品詞
            word = node.surface
            word_list.append(word)
        node = node.next
    return " ".join(word_list)

#例
# text = 'どれだけの天才でもどれだけの馬鹿でも自分一人だけの純粋な世界なんて存在しえないんだ。'
# print(wakati(text))  #=> どれ 天才 どれ 馬鹿 自分 一 人 純粋 世界 存在 し え ん

df["target"] = df['snnipet'].apply(wakati)

In [122]:
df["target"]

0     WEAR ウェア 日本 最大 ファッション コーディネート サイト モデル 俳優 ショップ ...
1                                                 キャッシュ
2     ファッション 英 fashion 英語 発音 fæ n ファシャン 仏 mode フランス ...
3     人気 キュレーションメディア 最新 ファッション 情報 レディース 集め 話題 ファッション...
4     ZOZOTOWN 8441 ブランド アイテム 公式 取扱う ファッション 通販 サイト ツ...
                            ...                        
93    ファッション 通販 haco ハコ 毎日 明日 昨日 びっくり できる 洋服 雑貨 プロジェ...
94    ファッション VOGUE JAPAN 公式 サイト 世界 ファッション コレクション はじめ...
95           Amazon 9 月 13 月 23 59 ファッション タイム セール 祭り 開催
96    Amazon ファッション タイム セール 祭り Amazon 開催 する 63 時間 セー...
97    レディース ファッション 通販 Re EDIT リエディ ファッション 通販 サイト 強く ...
Name: target, Length: 98, dtype: object

In [126]:
import mojimoji
df["target"] = df["target"].apply(mojimoji.zen_to_han)
df["target"]

0     WEAR ｳｪｱ 日本 最大 ﾌｧｯｼｮﾝ ｺｰﾃﾞｨﾈｰﾄ ｻｲﾄ ﾓﾃﾞﾙ 俳優 ｼｮｯ...
1                                                 ｷｬｯｼｭ
2     ﾌｧｯｼｮﾝ 英 fashion 英語 発音 fæ n ﾌｧｼｬﾝ 仏 mode ﾌﾗﾝｽ ...
3     人気 ｷｭﾚｰｼｮﾝﾒﾃﾞｨｱ 最新 ﾌｧｯｼｮﾝ 情報 ﾚﾃﾞｨｰｽ 集め 話題 ﾌｧｯｼ...
4     ZOZOTOWN 8441 ﾌﾞﾗﾝﾄﾞ ｱｲﾃﾑ 公式 取扱う ﾌｧｯｼｮﾝ 通販 ｻｲﾄ...
                            ...                        
93    ﾌｧｯｼｮﾝ 通販 haco ﾊｺ 毎日 明日 昨日 びっくり できる 洋服 雑貨 ﾌﾟﾛｼ...
94    ﾌｧｯｼｮﾝ VOGUE JAPAN 公式 ｻｲﾄ 世界 ﾌｧｯｼｮﾝ ｺﾚｸｼｮﾝ はじめ...
95           Amazon 9 月 13 月 23 59 ﾌｧｯｼｮﾝ ﾀｲﾑ ｾｰﾙ 祭り 開催
96    Amazon ﾌｧｯｼｮﾝ ﾀｲﾑ ｾｰﾙ 祭り Amazon 開催 する 63 時間 ｾｰ...
97    ﾚﾃﾞｨｰｽ ﾌｧｯｼｮﾝ 通販 Re EDIT ﾘｴﾃﾞｨ ﾌｧｯｼｮﾝ 通販 ｻｲﾄ 強...
Name: target, Length: 98, dtype: object

In [127]:
def normalize_number(text):
    # 連続した数字を0で置換
    replaced_text = re.sub(r'\d+', '0', text)
    return replaced_text

In [130]:
df["target"] = df["target"].apply(normalize_number)
df["target"].head()

0    WEAR ｳｪｱ 日本 最大 ﾌｧｯｼｮﾝ ｺｰﾃﾞｨﾈｰﾄ ｻｲﾄ ﾓﾃﾞﾙ 俳優 ｼｮｯ...
1                                                ｷｬｯｼｭ
2    ﾌｧｯｼｮﾝ 英 fashion 英語 発音 fæ n ﾌｧｼｬﾝ 仏 mode ﾌﾗﾝｽ ...
3    人気 ｷｭﾚｰｼｮﾝﾒﾃﾞｨｱ 最新 ﾌｧｯｼｮﾝ 情報 ﾚﾃﾞｨｰｽ 集め 話題 ﾌｧｯｼ...
4    ZOZOTOWN 0 ﾌﾞﾗﾝﾄﾞ ｱｲﾃﾑ 公式 取扱う ﾌｧｯｼｮﾝ 通販 ｻｲﾄ ﾂｹ...
Name: target, dtype: object

In [132]:
import os
import urllib.request
def download_stopwords(path):
    url = 'http://svn.sourceforge.jp/svnroot/slothlib/CSharp/Version1/SlothLib/NLP/Filter/StopWord/word/Japanese.txt'
    if os.path.exists(path):
        print('File already exists.')
    else:
        print('Downloading...')
        # Download the file from `url` and save it locally under `file_name`:
        urllib.request.urlretrieve(url, path)
        
def create_stopwords(file_path):
    stop_words = []
    for w in open(path, "r"):
        w = w.replace('\n','')
        if len(w) > 0:
          stop_words.append(w)
    return stop_words    
        
path = "stop_words.txt"
download_stopwords(path)
stop_words = create_stopwords(path)
print(stop_words)

Downloading...


In [143]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b')
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
feature_sparse
features

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 1, 0, ..., 0, 0, 0],
       [1, 2, 0, ..., 0, 0, 0],
       [3, 0, 0, ..., 0, 0, 0]])

In [145]:
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(672,) が単語数
(672,)
[600   0 397 511 438 610 664 137  98 314 170 202 508 394  83 339 286 572
 386  24]
600
ﾌｧｯｼｮﾝ 153
0 68
通販 52
ｻｲﾄ 41
ｱｲﾃﾑ 41
ﾌﾞﾗﾝﾄﾞ 36
ﾚﾃﾞｨｰｽ 33
人気 33
し 32
無料 24
公式 18
商品 18
ｺﾚｸｼｮﾝ 17
送料 16
い 16
紹介 14
最新 13
ﾄﾚﾝﾄﾞ 12
購入 12
fashion 12
新作 11
ｱｳﾀｰ 11
する 11
代 11
楽天 11
価格 11
ﾜﾝ 11
ﾒﾝｽﾞ 11
情報 11
ｼｮｯﾌﾟ 10
買い物 10
取り扱う 10
開催 9
rakuten 9
取り揃え 9
入荷 8
ｻｲｽﾞ 8
ｾｰﾙ 8
ﾆｭｰｽ 8
得 7
女性 7
ｽｶｰﾄ 7
ﾄｯﾌﾟｽ 7
ﾊﾞｯｸﾞ 7
ﾊﾟﾝﾂ 7
ﾋﾟｰｽ 7
ｼｭｰｽﾞ 7
税込 7
ﾍﾟｰｼﾞ 7
ｼｮｯﾋﾟﾝｸﾞ 6
いただけ 6
品揃え 6
流行 6
掲載 6
ﾁｪｯｸ 6
amazon 6
ｼﾞｬｹｯﾄ 6
おしゃれ 6
ｱﾍﾞﾆｭｰ 5
ｳｪｱ 5
ﾈｯﾄ 5
ｸｰﾎﾟﾝ 5
できる 5
ｶｼﾞｭｱﾙ 5
ｶﾃｺﾞﾘ 5
ｷｬｯｼｭ 5
洋服 5
ｱｰﾄ 5
ﾗﾝｷﾝｸﾞ 5
いる 5
手数 5
大人 5
小物 5
旧 5
ｺｰﾃﾞ 5
ﾗｲﾌｽﾀｲﾙ 5
多数 5
中心 4
ｲﾝ 4
以外 4
返品 4
配信 4
配送 4
最大 4
世界 4
ﾌﾟﾚｽ 4
一部 4
でき 4
ﾗｲﾝ 4
幅広く 4
ﾃﾞｨﾉｽ 4
販売 4
ｺｰﾃﾞｨﾈｰﾄ 4
ｽｰﾂ 4
ｵｰﾙ 4
ｵﾝ 4
ﾌﾟﾁﾌﾟﾗ 4
ｺｰﾄ 4
秋冬 4
あり 4
ｽﾅｯﾌﾟ 4
登場 4
ﾋﾞｭｰﾃｨ 4
取扱う 4
ｻｰﾋﾞｽ 3
ｷｯｽﾞ 3
zozotown 3
ｵｰｸｼｮﾝ 3
ｱｸｾｻﾘｰ 3
ｱﾏｿﾞﾝ 3
ご覧 3
ｲﾍﾞﾝﾄ 3
ｲﾝﾅｰ 3
ﾚﾎﾟｰﾄ 3
ｺｽﾒ 3
まとめ 3
ｱｳﾄﾚｯﾄ 3
百貨 3
店舗 3
届け 3
定番 3
安値 3
提供 3
安く 3
新品 3
日本 3
旬 3
最短 3
圧倒 3
ﾔﾌｵｸ 3
海外 3
古着 3
即日 3
類似 3
ﾓﾃﾞﾙ 3
素材 3


In [148]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(norm='l2', sublinear_tf=True)
tfidf = tfidf_transformer.fit_transform(feature_sparse)
tfidf

<98x672 sparse matrix of type '<class 'numpy.float64'>'
	with 1745 stored elements in Compressed Sparse Row format>

In [149]:
features = np.array(tfidf.todense())
feature_sparse
features
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(672,) が単語数
(672,)
[600   0 397 438 483 610 511 137 664  98 314 508 170 394 202 339  83 247
 270 297]
600
ﾌｧｯｼｮﾝ 8.348431451710944
0 5.989116859913201
通販 5.480465662904854
ｱｲﾃﾑ 5.001266559625482
ｷｬｯｼｭ 5.0
ﾌﾞﾗﾝﾄﾞ 4.993802492023004
ｻｲﾄ 4.936577817333788
人気 4.6712626787439016
ﾚﾃﾞｨｰｽ 4.241203982018595
し 4.024761909642024
無料 3.5426151255142653
ｺﾚｸｼｮﾝ 3.0196927021010085
公式 2.879353478678999
送料 2.7685444271031825
商品 2.766010304298127
紹介 2.669684892967058
い 2.630071151654917
情報 2.479275173023307
新作 2.3466599900691576
楽天 2.343134602350031
fashion 2.3374431627341146
ﾍﾟｰｼﾞ 2.3121685976023354
最新 2.2913439889203553
ﾒﾝｽﾞ 2.2497770304808236
取り扱う 2.249248410928829
ﾄﾚﾝﾄﾞ 2.159453149674609
rakuten 2.0999437820050195
買い物 2.0816003492289648
購入 1.9965552950486918
ｱｳﾀｰ 1.980988464327639
開催 1.9803970513639755
価格 1.929715128285037
入荷 1.9203549912879558
ｼｮｯﾌﾟ 1.864263634854858
代 1.854086198647504
類似 1.7673727935326942
する 1.761267644913004
ﾜﾝ 1.7533956208840145
税込 1.6954975642304304
おしゃれ 1.6579625859419576
取り揃え

In [151]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b', max_df=50, min_df=3)
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(145,) が単語数
(145,)
[  0  78  86 109 132 142  20  12  63  33  25 107  77   7  67  57  75 122
   2  23]
0
0 68
通販 52
ｱｲﾃﾑ 41
ｻｲﾄ 41
ﾌﾞﾗﾝﾄﾞ 36
ﾚﾃﾞｨｰｽ 33
人気 33
し 32
無料 24
商品 18
公式 18
ｺﾚｸｼｮﾝ 17
送料 16
い 16
紹介 14
最新 13
購入 12
ﾄﾚﾝﾄﾞ 12
fashion 12
価格 11
代 11
新作 11
楽天 11
する 11
ｱｳﾀｰ 11
情報 11
ﾜﾝ 11
ﾒﾝｽﾞ 11
取り扱う 10
ｼｮｯﾌﾟ 10
買い物 10
rakuten 9
取り揃え 9
開催 9
ﾆｭｰｽ 8
ｻｲｽﾞ 8
ｾｰﾙ 8
入荷 8
ﾄｯﾌﾟｽ 7
ﾊﾞｯｸﾞ 7
税込 7
ﾊﾟﾝﾂ 7
ｽｶｰﾄ 7
ﾋﾟｰｽ 7
ﾍﾟｰｼﾞ 7
ｼｭｰｽﾞ 7
得 7
女性 7
流行 6
いただけ 6
掲載 6
おしゃれ 6
ﾁｪｯｸ 6
品揃え 6
ｼｮｯﾋﾟﾝｸﾞ 6
amazon 6
ｼﾞｬｹｯﾄ 6
ﾈｯﾄ 5
ｸｰﾎﾟﾝ 5
ｱﾍﾞﾆｭｰ 5
ｷｬｯｼｭ 5
ｶﾃｺﾞﾘ 5
ｶｼﾞｭｱﾙ 5
旧 5
できる 5
ﾗﾝｷﾝｸﾞ 5
手数 5
ｺｰﾃﾞ 5
洋服 5
ﾗｲﾌｽﾀｲﾙ 5
小物 5
ｳｪｱ 5
いる 5
ｱｰﾄ 5
大人 5
多数 5
幅広く 4
ｽﾅｯﾌﾟ 4
ｺｰﾄ 4
取扱う 4
以外 4
ｺｰﾃﾞｨﾈｰﾄ 4
最大 4
ｽｰﾂ 4
ﾌﾟﾚｽ 4
ﾗｲﾝ 4
返品 4
ｵﾝ 4
あり 4
ｲﾝ 4
配送 4
配信 4
ｵｰﾙ 4
ﾋﾞｭｰﾃｨ 4
ﾌﾟﾁﾌﾟﾗ 4
中心 4
販売 4
でき 4
一部 4
秋冬 4
登場 4
ﾔﾌｵｸ 3
出品 3
まとめ 3
即日 3
ﾎﾞﾄﾑｽ 3
tv 3
ご覧 3
古着 3
zozotown 3
交換 3
最短 3
圧倒 3
落札 3
ｼﾞｭｴﾘｰ 3
ｺｽﾒ 3
ｷｯｽﾞ 3
ｵｰｸｼｮﾝ 3
ｲﾝﾅｰ 3
ｲﾍﾞﾝﾄ 3
ｱﾏｿﾞﾝ 3
ｱｳﾄﾚｯﾄ 3
類似 3
雑貨 3
除く 3
ﾄﾞﾚｽ 3
ﾚﾎﾟｰﾄ 3
訳あり 3
翌日 3
安く 3
美容 3
海外 3
ｽｳｪｯﾄ 3
旬 3
日本 3
新品 3
ﾌｧｽﾄ 3


In [158]:
np.sum(features,axis=1)

array([10,  1,  7, 16, 21, 10, 15, 20, 11, 17,  2,  1, 12, 13, 14, 14, 15,
       12, 14, 15,  1, 24, 15, 24, 16, 15,  7, 16, 13, 18,  1, 15, 19,  7,
       12, 22, 11,  6,  7,  3,  7, 12,  7,  1, 18,  8, 15, 15, 12,  1, 11,
        4,  7,  6, 10, 15, 15, 14, 22, 19, 18, 22, 14, 22, 13,  7,  7,  5,
        7, 15, 22, 22, 14, 22, 17, 15,  7, 10, 15,  8,  2, 14,  6,  6,  7,
        8,  4, 10,  1, 18,  4,  9,  9,  4, 11,  7, 17, 17])

どの文章も何かしらの特徴量はもっている．

In [161]:
print(features[1,:])
print(np.argmax(features[1,:]))
print(cv.get_feature_names()[np.argmax(features[1,:])])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
100
ｷｬｯｼｭ


In [162]:
np.sum(features,axis=0)[100]

5

In [186]:
cv.get_feature_names()

['0',
 'amazon',
 'fashion',
 'rakuten',
 'tv',
 'zozotown',
 'あり',
 'い',
 'いただけ',
 'いる',
 'おしゃれ',
 'ご覧',
 'し',
 'する',
 'でき',
 'できる',
 'まとめ',
 '一部',
 '中心',
 '交換',
 '人気',
 '代',
 '以外',
 '価格',
 '入荷',
 '公式',
 '出品',
 '即日',
 '取り扱う',
 '取り揃え',
 '取扱う',
 '古着',
 '品揃え',
 '商品',
 '圧倒',
 '多数',
 '大人',
 '女性',
 '安く',
 '安値',
 '定番',
 '小物',
 '届け',
 '幅広い',
 '幅広く',
 '店舗',
 '得',
 '情報',
 '手数',
 '掲載',
 '提供',
 '新作',
 '新品',
 '日本',
 '旧',
 '旬',
 '最大',
 '最新',
 '最短',
 '楽天',
 '洋服',
 '流行',
 '海外',
 '無料',
 '登場',
 '秋冬',
 '税込',
 '紹介',
 '美容',
 '翌日',
 '落札',
 '訳あり',
 '財布',
 '販売',
 '買い物',
 '購入',
 '返品',
 '送料',
 '通販',
 '配信',
 '配送',
 '開催',
 '除く',
 '雑貨',
 '類似',
 'ｱｰﾄ',
 'ｱｲﾃﾑ',
 'ｱｳﾀｰ',
 'ｱｳﾄﾚｯﾄ',
 'ｱﾍﾞﾆｭｰ',
 'ｱﾏｿﾞﾝ',
 'ｲﾍﾞﾝﾄ',
 'ｲﾝ',
 'ｲﾝﾅｰ',
 'ｳｪｱ',
 'ｵｰｸｼｮﾝ',
 'ｵｰﾙ',
 'ｵﾝ',
 'ｶｼﾞｭｱﾙ',
 'ｶﾃｺﾞﾘ',
 'ｷｬｯｼｭ',
 'ｷｯｽﾞ',
 'ｸｰﾎﾟﾝ',
 'ｺｰﾃﾞ',
 'ｺｰﾃﾞｨﾈｰﾄ',
 'ｺｰﾄ',
 'ｺｽﾒ',
 'ｺﾚｸｼｮﾝ',
 'ｻｲｽﾞ',
 'ｻｲﾄ',
 'ｼｭｰｽﾞ',
 'ｼｮｯﾋﾟﾝｸﾞ',
 'ｼｮｯﾌﾟ',
 'ｼﾞｬｹｯﾄ',
 'ｼﾞｭｴﾘｰ',
 'ｽｰﾂ',
 'ｽｳｪｯﾄ',
 'ｽｶｰﾄ',
 'ｽﾅｯﾌﾟ',
 'ｾｰﾙ',
 'ﾁｪｯｸ',
 'ﾄｯﾌﾟｽ',
 'ﾄﾚﾝﾄﾞ',
 'ﾄﾞﾚｽ',
 'ﾆｭ

In [187]:
df.site_name

0                    WEAR: ファッションコーディネート
2                     ファッション - Wikipedia
3            ファッションまとめ（レディース） - ZOZOTOWN
4                       ファッション通販ZOZOTOWN
5           ファッション通販SHOPLIST（ショップリスト ...
                     ...                
93    ファッション通販のhaco! | ハコ！毎日のお洋服と明日の ...
94              Fashion - ファッション - VOGUE
95     Amazonファッションタイムセール祭りでビジネスバッグが ...
96          Amazon ファッションタイムセール祭り - アマゾン
97            レディースファッション通販 Re:EDIT‐リエディ
Name: site_name, Length: 91, dtype: object