参考
https://hibiki-press.tech/python/mecab/5153

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
import MeCab
import pandas as pd
import numpy as np
import re

In [5]:
keyword = 'あっぷる'
filename = '../'+keyword+ '.csv'

In [6]:
df = pd.read_csv(filename)
df.head()

keyword           site_name snnipet  \
0    あっぷる           Apple（日本）   キャッシュ   
1    あっぷる  iPhone - Apple（日本）   キャッシュ   
2    あっぷる    Apple Storeオンライン   キャッシュ   
3    あっぷる    iPad - Apple（日本）   キャッシュ   
4    あっぷる   Watch - Apple（日本）   キャッシュ   

                                              URL  ranking  
0         =HYPERLINK("https://www.apple.com/jp/")        1  
1  =HYPERLINK("https://www.apple.com/jp/iphone/")        2  
2    =HYPERLINK("https://www.apple.com/jp/store")        3  
3    =HYPERLINK("https://www.apple.com/jp/ipad/")        4  
4   =HYPERLINK("https://www.apple.com/jp/watch/")        5

https://www.delftstack.com/ja/howto/python-pandas/how-to-delete-dataframe-row-in-pandas-based-on-column-value/

In [7]:
cb1 = (df['snnipet'] == 'キャッシュ' )
cb2 = (df['snnipet'] == '類似ページ' )
condition_bool = (cb1 | cb2)
df.drop(df[ condition_bool == True ].index, inplace=True)
df

keyword                                       site_name  \
7     あっぷる                         Apple Music - Apple（日本）   
9     あっぷる                               Apple - Wikipedia   
15    あっぷる        アップル(Apple) - 【メルカリ】No.1フリマアプリ - Mercari   
16    あっぷる                    Appleに関する最新記事831件 | WIRED.jp   
20    あっぷる                        Apple Arcade - Apple（日本）   
29    あっぷる            アップル（読み）あっぷる（英語表記）Apple Inc. - コトバンク   
30    あっぷる                              あっぷる新着情報 - NBC長崎放送   
31    あっぷる            介護の応援団【あっぷる】 姫路市 - 加古川市 - たつの市 - 明石市   
36    あっぷる               あっぷる (@ririka0221apple) | Twitter   
37    あっぷる                            Apple（アップル） - 価格.com   
38    あっぷる                                     あっぷるぐりむグループ   
39    あっぷる                            アップルの一覧 | ギズモード・ジャパン   
41    あっぷる                              コンタクトレンズ通販 レンズアップル   
42    あっぷる                           Apple TV+ - Apple（日本）   
46    あっぷる                    アップル、「iOS 15」発表 - ケータイ Watch   
47    あっぷる                                  | 介護の応援団【あっぷる】   
48    あっぷる                   あっぷるタイムス最新号更新しました - アップルハウジング   
49    あっぷる                                アップル - Wikipedia   
50    あっぷる                       かふぇ あっぷる - 人形町/カフェ | 食べログ   
51    あっぷる     GRANNY SMITH APPLE PIE & COFFEE グラニースミス ...   
53    あっぷる                        iPhone SEを購入 - Apple（日本）   
57    あっぷる                                   坂城店 | 美容室あっぷる   
58    あっぷる              「アップルストア」の検索結果 - 【楽天市場】ジャンルトップ ...   
59    あっぷる                          車販売 - 中古車買取・中古車査定のアップル   
62    あっぷる                株式会社あっぷる ソーシャルメディアポリシー - 117グループ   
63    あっぷる                               秋田プレミアムあっぷる | TOP   
65    あっぷる                 Appleのスマートフォン・格安スマホ 最新人気機種ランキング   
66    あっぷる                   最新の apple ニュース - Engadget 日本版   
67    あっぷる        (株) あっぷる関西 尼崎南店｜ (兵庫県尼崎市) 中古車なら - グー ...   
68    あっぷる                                      アップル引越センター   
69    あっぷる                         APPLE｜マネキン トルソ 株式会社アップル   
70    あっぷる                          元気あっぷる体操 - 青森放送局 - NHK   
75    あっぷる                               秋田プレミアムあっぷる | TOP   
76    あっぷる                アップル【AAPL】：掲示板/株価 - Yahoo!ファイナンス   
77    あっぷる                         アップル引越センター | 公式サイトなら最安値   
78    あっぷる               株式会社アップル コーポレートサイト｜アパマンショップFC ...   
79    あっぷる                  英会話｜大阪・梅田と難波の英会話スクール【アップルk ...   
80    あっぷる         アップル四日市ときわ店 (三重県四日市) の詳細 - 中古車 - グー ...   
83    あっぷる                        店舗を探す - 中古車買取・中古車査定のアップル   
84    あっぷる                            中古車買取・中古車査定のアップル【公式】   
85    あっぷる                                   あっぷるワイド - NHK   
86    あっぷる             あっぷる関西 グループ公式 | 西日本最大級の国産車・輸入車の ...   
87    あっぷる                               個別教室のアップル ／宮城県仙台市   
88    あっぷる               Apple(アップル)のタブレットPC 製品一覧 - 価格.com   
89    あっぷる            アップルアンドローゼス: 【Apple&Roses】薔薇のタルト ...   
90    あっぷる                               アップルワールド旅行会社専用サイト   
91    あっぷる                        味処あっぷる亭 - 上伊田/居酒屋 | 食べログ   
92    あっぷる                       ‎「Apple Store」をApp Storeで   
93    あっぷる                      無料査定申込み - 中古車買取・中古車査定のアップル   
94    あっぷる    AAPL:NASDAQ GS 株価 - アップル - Bloomberg Markets   
95    あっぷる           ホットアップルパイ | メニュー情報 | McDonald's Japan   
96    あっぷる  アップル Apple Apple Pencil 第2世代 [MU8F2J/A] - ヨドバシ   
97    あっぷる   アップル Apple MK0C2J/A [Apple Pencil] 通販【全品無料配達】   
99    あっぷる                      津軽のお宿 南田温泉ホテルアップルランド【公式HP】   

                                              snnipet  \
7                        Apple Musicはどうすれば聴くことができますか？   
9   Apple Inc. （アップル）は、カリフォルニア州クパチーノに本社を置くアメリカ合衆国の...   
15  アップル - アップルはアメリカの企業で、日本においてもさまざまな製品やサービスが人気を集め...   
16  Apple（アップル）は、インターネット関連製品、デジタル家庭電化製品、ソフトウェア製品を開...   
20                          どのくらいのペースで新しいゲームが追加されますか？   
29  日本大百科全書(ニッポニカ) - アップルの用語解説 - アメリカのコンピュータ会社。本社所...   
30  あっぷる新着情報. 3/19（木）ささみと豆もやしの香草和え他. 礒永 由紀 先生 料理レシ...   
31           介護保険申請代行・ケアプラン作成・介護サービスなら117グループ「あっぷる」へ.   
36  The latest Tweets from あっぷる (@ririka0221apple)...   
37  Apple（アップル）の製品をカテゴ

In [8]:
def text_to_words(text):
    tagger = MeCab.Tagger("-O wakati")
    return tagger.parse(text).split()

In [9]:
texts = df['snnipet'].tolist()
texts
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

['Apple Musicはどうすれば聴くことができますか？',
 'Apple Inc. （アップル）は、カリフォルニア州クパチーノに本社を置くアメリカ合衆国の多国籍テクノロジー企業である。デジタル家庭電化製品、ソフトウェア、オンラインサービスの開発・販売を行っている。',
 'アップル - アップルはアメリカの企業で、日本においてもさまざまな製品やサービスが人気を集めています。デザイナーを中心に人気のあるMac、スマートフォンの認知度を広めたとも言えるiPhone、タブレット端末のiPadなどがあります。',
 'Apple（アップル）は、インターネット関連製品、デジタル家庭電化製品、ソフトウェア製品を開発・販売する多国籍企業。代表的なハードウェア製品として、スマートフォンのiPhone、タブレット型情報端末のiPad、パーソナルコンピュータのMacintosh、携帯\xa0...',
 'どのくらいのペースで新しいゲームが追加されますか？',
 '日本大百科全書(ニッポニカ) - アップルの用語解説 - アメリカのコンピュータ会社。本社所在地はカリフォルニア州クパーチーノ。カナダ産のリンゴであるマッキントッシュMacintoshに由来するリンゴのロゴマークで有名。2007年1月に社名を従来のアップル・\xa0...',
 'あっぷる新着情報. 3/19（木）ささみと豆もやしの香草和え他. 礒永 由紀 先生 料理レシピはこちら ... 出演者. NBCあっぷるtwitter. あっぷるfacebook. あっぷるテレPlus+. あっぷる. 番組でご紹介した情報 · 出演者の紹介 · あっぷるクッキング\xa0...',
 '介護保険申請代行・ケアプラン作成・介護サービスなら117グループ「あっぷる」へ.',
 'The latest Tweets from あっぷる (@ririka0221apple). PKAのA（@pka_123） サブ（@aptan_21）  あぽちゃんねる↪︎ https://t.co/P1Ecuu5iUq.',
 'Apple（アップル）の製品をカテゴリから探すことができます。カテゴリごとの人気売れ筋製品ランキングや、新着ニュースなど、Apple（アップル）の製品に関する情報はここでチェック！',
 '株式会社あっぷるアイビー. ［

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(385,) が単語数
(385,)
[ 28 121  68 127 203 315 366 368  40 218 334  56 311 323  31 348 347 247
 227 214]
28
apple 15
アップル 12
あっぷる 4
アップルの車買取 3
レビュー 3
無料で自動車の買取相場が分かります 3
車のことなら国内最大級の買取実績アップルへ 3
車査定サービス 3
ios 3
介護サービスなら117グループ 2
秋田あっぷるで秋田の情報を知る 2
pencil 2
温泉 2
画像も盛り沢山 2
com 2
英会話 2
翌日お届け実施中 2
即日 2
会社 2
今なら日本全国へ全品配達料金無料 2
介護保険申請代行 2
あっぷるぐりむグループ 2
inc 2
aapl 2
秋田美人 2
秋田県のタウン情報誌あっぷるが発信する秋田県の食べ処やラーメン 2
ケアプラン作成 2
元気あっぷる体操 2
デジタル家庭電化製品 2
ランキング 2
ご購入でゴールドポイント取得 2
の通販ならヨドバシカメラの公式サイト 2
ヨドバシ 2
お得なクーポンまで情報満載サイト 2
団体 2
販売開始 2
800 2
アップル発表イベント直前に 1
の公式企業サイトです 1
アップルは1人暮らし 1
アップルは8日 1
アップルはアメリカの企業で 1
アップルアンドローゼス 1
アップルストア 1
アップル引越センター 1
のホームページです 1
のタブレットpc製品一覧 1
の掲示板 1
アップルハウジングは 1
のスマートフォンをランキング形式でご紹介 1
のこと 1
の店舗情報は食べログでチェック 1
を発表した 1
の株価 1
の製品に関する情報はここでチェック 1
を立ち上げ 1
アップルの用語解説 1
の製品をカテゴリから探すことができます 1
の詳細な予想公開 1
アップルの中古車買取 1
は広大な津軽平野と岩木山を眺めるりんごづくしの温泉旅館です 1
アップルに関する記事一覧ページです 1
アップルkランゲージ 1
アップルapp 1
やきとり居酒屋きらび本店 1
りんごで作ったアップルタルトやアップルパイを販売しています 1
を開発しました 1
駅前の大人スクール 1
エンターテイメントの情報まで 1
アパート 1
アパートの仲介店舗を多

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(tokenizer=text_to_words, ngram_range=(1,2))
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(2736,) が単語数
(2736,)
[ 889  363   31  450 1090  757 1138 1520   33  854 2681 1012  977  638
 2044 1013  551  604  517  702]
889
の 118
、 105
. 93
。 74
を 47
で 47
アップル 43
・ 40
. . 40
に 38
！ 31
ます 30
は 29
が 28
情報 26
ます 。 26
あっぷる 24
お 23
」 23
し 22
「 22
車 20
て 18
や 18
も 18
apple 16
と 16
な 14
（ 14
） 14
1 13
など 12
なら 12
こと 12
た 12
ご 11
です 11
会社 11
買取 11
サービス 10
販売 10
秋田 10
です 。 9
し て 9
は 、 9
) 9
する 9
( 9
製品 9
県 8
· 8
/ 8
車 の 8
日本 8
無料 8
へ 8
でき 7
でき ます 7
介護 7
企業 6
まで 6
査定 6
株式 6
サイト 6
／ 6
の 買取 6
お 届け 6
- 6
届け 6
人気 6
店舗 5
年 5
中 5
など 、 5
青森 5
予約 5
実績 5
から 5
か 5
国内 5
し た 5
品 5
さ 5
ホテル 5
株式 会社 5
ランキング 5
車 買取 5
アップル は 5
アップル の 5
, 5
グループ 5
（ アップル 5
最大 5
！ ！ 5
こと が 5
2 5
者 5
a 5
の こと 5
レンズ 4
車 査定 4
無料 で 4
の 製品 4
ヨドバシ 4
の 情報 4
査定 サービス 4
ある 4
こと なら 4
し ます 4
県 の 4
相場 が 4
相場 4
秋田 県 4
て い 4
て いる 4
分かり ます 4
分かり 4
で ご 4
級 4
級 の 4
で 自動 4
い 4
が 分かり 4
が でき 4
価格 4
得 4
か ？ 4
自動 4
自動 車 4
製 4
製 品 4
: 4
いる 4
い ます 4
温泉 4
買取 ・ 4
スマート フォン 4
日 4
フォン 4
？ 4
スマート 4
開発 4
最新 4
アメリカ 4
. あっぷる 4
限定 4
、 お 4
月 4
サービス 。 4
情報 、 4


In [16]:
texts = df['snnipet']
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

https://qiita.com/chamao/items/7edaba62b120a660657e
これみたら最強．ほぼこれ+max_dfの設定

In [36]:
import MeCab
def wakati(text):
    tagger = MeCab.Tagger('')
    tagger.parse('') 
    node = tagger.parseToNode(text)
    word_list = []
    while node:
        pos = node.feature.split(",")[0]
        if pos in ["名詞", "動詞", "形容詞"]:   # 対象とする品詞
            print(pos, node.surface)
            word = node.surface
            word_list.append(word)
        node = node.next
    return " ".join(word_list)

#例
# text = 'どれだけの天才でもどれだけの馬鹿でも自分一人だけの純粋な世界なんて存在しえないんだ。'
# print(wakati(text))  #=> どれ 天才 どれ 馬鹿 自分 一 人 純粋 世界 存在 し え ん

df["target"] = df['snnipet'].apply(wakati)

名詞 Apple
名詞 Music
動詞 すれ
動詞 聴く
名詞 こと
動詞 でき
名詞 Apple
名詞 Inc
名詞 アップル
名詞 カリフォルニア
名詞 州
名詞 クパチーノ
名詞 本社
動詞 置く
名詞 アメリカ
名詞 合衆
名詞 国籍
名詞 テクノロジー
名詞 企業
動詞 ある
名詞 デジタル
名詞 家庭
名詞 電化
名詞 ソフトウェア
名詞 オン
名詞 ライン
名詞 サービス
名詞 開発
名詞 販売
動詞 行っ
動詞 いる
名詞 アップル
名詞 アップル
名詞 アメリカ
名詞 企業
名詞 日本
動詞 おい
名詞 製品
名詞 サービス
名詞 人気
動詞 集め
動詞 い
名詞 デザイナー
名詞 中心
名詞 人気
動詞 ある
名詞 Mac
名詞 フォン
名詞 認知
名詞 度
動詞 広め
動詞 言える
名詞 iPhone
名詞 タブレット
名詞 端末
名詞 iPad
動詞 あり
名詞 Apple
名詞 アップル
名詞 インターネット
名詞 関連
名詞 デジタル
名詞 家庭
名詞 電化
名詞 ソフトウェア
名詞 製品
名詞 開発
名詞 販売
動詞 する
名詞 国籍
名詞 企業
名詞 代表
名詞 ハードウェア
動詞 し
名詞 フォン
名詞 iPhone
名詞 タブレット
名詞 情報
名詞 端末
名詞 iPad
名詞 パーソナル
名詞 コンピュータ
名詞 Macintosh
名詞 携帯
名詞 ペース
形容詞 新しい
名詞 ゲーム
名詞 追加
動詞 さ
名詞 日本
名詞 百科
名詞 全書
名詞 ニッポニカ
名詞 アップル
名詞 用語
名詞 解説
名詞 アメリカ
名詞 コンピュータ
名詞 会社
名詞 本社
名詞 所在
名詞 地
名詞 カリフォルニア
名詞 州
名詞 クパーチーノ
名詞 カナダ
名詞 リンゴ
動詞 ある
名詞 マッキントッシュ
名詞 Macintosh
名詞 由来
動詞 する
名詞 リンゴ
名詞 ロゴ
名詞 マーク
名詞 2007
名詞 年
名詞 1
名詞 月
名詞 社名
名詞 従来
名詞 アップル
名詞 あっぷる
名詞 新着
名詞 情報
名詞 3
名詞 19
名詞 木
名詞 ささみ
名詞 豆もやし
名詞 香草
名詞 他
名詞 礒
名詞 永
名詞 由紀
名詞 先生
名詞 料理
名詞 レシピ
名詞 出演
名詞 NBC
名詞 あっぷる
名詞 twitter
名詞

In [18]:
df["target"]

7                               Apple Music すれ 聴く こと でき
9     Apple Inc アップル カリフォルニア 州 クパチーノ 本社 置く アメリカ 合衆 国...
15    アップル アップル アメリカ 企業 日本 おい 製品 サービス 人気 集め い デザイナー ...
16    Apple アップル インターネット 関連 デジタル 家庭 電化 ソフトウェア 製品 開発 ...
20                                     ペース 新しい ゲーム 追加 さ
29    日本 百科 全書 ニッポニカ アップル 用語 解説 アメリカ コンピュータ 会社 本社 所在...
30    あっぷる 新着 情報 3 19 木 ささみ 豆もやし 香草 他 礒 永 由紀 先生 料理 レ...
31          介護 保険 申請 代行 ケア プラン 作成 介護 サービス 117 グループ あっぷる
36    The latest Tweets from あっぷる ririka 0221 apple ...
37    Apple アップル 製品 カテゴリ 探す こと でき カテゴリ 人気 売れ筋 製品 ランキ...
38    株式 会社 あっぷる アイビー グループ イタリアン レストラン ピッツェリア 焼肉 バーン...
39    アップル 関する 記事 一覧 ページ GIZMODO JAPAN 最新 フォン デジタル デ...
41    コンタクト レンズ 通販 レンズ アップル 安心 便利 コンタクト レンズ オン ライン シ...
42                                          すれ 観る こと でき
46    アップル 8 日本 時間 開発 イベント WWDC 21 iOS 15 発表 し 今秋 提供...
47    介護 保険 申請 代行 ケア プラン 作成 介護 サービス 117 グループ あっぷる 問い...
48    アップル ハウジング 福岡 新築 住宅 リフォーム マンション リフォーム 通し 人 環境 ...
49    アップル apple 英語 リンゴ 林檎 こと 目次 1 会社 団体 1 1 架空 

In [19]:
import mojimoji
df["target"] = df["target"].apply(mojimoji.zen_to_han)
df["target"]

7                               Apple Music すれ 聴く こと でき
9     Apple Inc ｱｯﾌﾟﾙ ｶﾘﾌｫﾙﾆｱ 州 ｸﾊﾟﾁｰﾉ 本社 置く ｱﾒﾘｶ 合衆...
15    ｱｯﾌﾟﾙ ｱｯﾌﾟﾙ ｱﾒﾘｶ 企業 日本 おい 製品 ｻｰﾋﾞｽ 人気 集め い ﾃﾞｻ...
16    Apple ｱｯﾌﾟﾙ ｲﾝﾀｰﾈｯﾄ 関連 ﾃﾞｼﾞﾀﾙ 家庭 電化 ｿﾌﾄｳｪｱ 製品 ...
20                                   ﾍﾟｰｽ 新しい ｹﾞｰﾑ 追加 さ
29    日本 百科 全書 ﾆｯﾎﾟﾆｶ ｱｯﾌﾟﾙ 用語 解説 ｱﾒﾘｶ ｺﾝﾋﾟｭｰﾀ 会社 本社...
30    あっぷる 新着 情報 3 19 木 ささみ 豆もやし 香草 他 礒 永 由紀 先生 料理 ﾚ...
31      介護 保険 申請 代行 ｹｱ ﾌﾟﾗﾝ 作成 介護 ｻｰﾋﾞｽ 117 ｸﾞﾙｰﾌﾟ あっぷる
36    The latest Tweets from あっぷる ririka 0221 apple ...
37    Apple ｱｯﾌﾟﾙ 製品 ｶﾃｺﾞﾘ 探す こと でき ｶﾃｺﾞﾘ 人気 売れ筋 製品 ...
38    株式 会社 あっぷる ｱｲﾋﾞｰ ｸﾞﾙｰﾌﾟ ｲﾀﾘｱﾝ ﾚｽﾄﾗﾝ ﾋﾟｯﾂｪﾘｱ 焼肉...
39    ｱｯﾌﾟﾙ 関する 記事 一覧 ﾍﾟｰｼﾞ GIZMODO JAPAN 最新 ﾌｫﾝ ﾃﾞｼ...
41    ｺﾝﾀｸﾄ ﾚﾝｽﾞ 通販 ﾚﾝｽﾞ ｱｯﾌﾟﾙ 安心 便利 ｺﾝﾀｸﾄ ﾚﾝｽﾞ ｵﾝ ﾗ...
42                                          すれ 観る こと でき
46    ｱｯﾌﾟﾙ 8 日本 時間 開発 ｲﾍﾞﾝﾄ WWDC 21 iOS 15 発表 し 今秋 ...
47    介護 保険 申請 代行 ｹｱ ﾌﾟﾗﾝ 作成 介護 ｻｰﾋﾞｽ 117 ｸﾞﾙｰﾌﾟ あっぷ...
48    ｱｯﾌﾟﾙ ﾊｳｼﾞﾝｸﾞ 福岡 新築 住宅 ﾘﾌｫｰﾑ ﾏﾝｼｮﾝ ﾘﾌｫｰﾑ 通し 人 ...
49    ｱｯﾌﾟﾙ apple 英語 ﾘﾝｺﾞ 林檎 こと 目次 1 会社 団体 1 1 架

In [23]:
def normalize_number(text):
    # 連続した数字を0で置換
    replaced_text = re.sub(r'\d+', '0', text)
    return replaced_text

In [29]:
df["target"] = df["target"].apply(normalize_number)
df["target"].head()
df["target"]
# df["target"][57]

7                               Apple Music すれ 聴く こと でき
9     Apple Inc ｱｯﾌﾟﾙ ｶﾘﾌｫﾙﾆｱ 州 ｸﾊﾟﾁｰﾉ 本社 置く ｱﾒﾘｶ 合衆...
15    ｱｯﾌﾟﾙ ｱｯﾌﾟﾙ ｱﾒﾘｶ 企業 日本 おい 製品 ｻｰﾋﾞｽ 人気 集め い ﾃﾞｻ...
16    Apple ｱｯﾌﾟﾙ ｲﾝﾀｰﾈｯﾄ 関連 ﾃﾞｼﾞﾀﾙ 家庭 電化 ｿﾌﾄｳｪｱ 製品 ...
20                                   ﾍﾟｰｽ 新しい ｹﾞｰﾑ 追加 さ
29    日本 百科 全書 ﾆｯﾎﾟﾆｶ ｱｯﾌﾟﾙ 用語 解説 ｱﾒﾘｶ ｺﾝﾋﾟｭｰﾀ 会社 本社...
30    あっぷる 新着 情報 0 0 木 ささみ 豆もやし 香草 他 礒 永 由紀 先生 料理 ﾚｼ...
31        介護 保険 申請 代行 ｹｱ ﾌﾟﾗﾝ 作成 介護 ｻｰﾋﾞｽ 0 ｸﾞﾙｰﾌﾟ あっぷる
36    The latest Tweets from あっぷる ririka 0 apple PKA...
37    Apple ｱｯﾌﾟﾙ 製品 ｶﾃｺﾞﾘ 探す こと でき ｶﾃｺﾞﾘ 人気 売れ筋 製品 ...
38    株式 会社 あっぷる ｱｲﾋﾞｰ ｸﾞﾙｰﾌﾟ ｲﾀﾘｱﾝ ﾚｽﾄﾗﾝ ﾋﾟｯﾂｪﾘｱ 焼肉...
39    ｱｯﾌﾟﾙ 関する 記事 一覧 ﾍﾟｰｼﾞ GIZMODO JAPAN 最新 ﾌｫﾝ ﾃﾞｼ...
41    ｺﾝﾀｸﾄ ﾚﾝｽﾞ 通販 ﾚﾝｽﾞ ｱｯﾌﾟﾙ 安心 便利 ｺﾝﾀｸﾄ ﾚﾝｽﾞ ｵﾝ ﾗ...
42                                          すれ 観る こと でき
46    ｱｯﾌﾟﾙ 0 日本 時間 開発 ｲﾍﾞﾝﾄ WWDC 0 iOS 0 発表 し 今秋 提供...
47    介護 保険 申請 代行 ｹｱ ﾌﾟﾗﾝ 作成 介護 ｻｰﾋﾞｽ 0 ｸﾞﾙｰﾌﾟ あっぷる ...
48    ｱｯﾌﾟﾙ ﾊｳｼﾞﾝｸﾞ 福岡 新築 住宅 ﾘﾌｫｰﾑ ﾏﾝｼｮﾝ ﾘﾌｫｰﾑ 通し 人 ...
49    ｱｯﾌﾟﾙ apple 英語 ﾘﾝｺﾞ 林檎 こと 目次 0 会社 団体 0 0 架

In [30]:
import os
import urllib.request
def download_stopwords(path):
    url = 'http://svn.sourceforge.jp/svnroot/slothlib/CSharp/Version1/SlothLib/NLP/Filter/StopWord/word/Japanese.txt'
    if os.path.exists(path):
        print('File already exists.')
    else:
        print('Downloading...')
        # Download the file from `url` and save it locally under `file_name`:
        urllib.request.urlretrieve(url, path)
        
def create_stopwords(file_path):
    stop_words = []
    for w in open(path, "r"):
        w = w.replace('\n','')
        if len(w) > 0:
          stop_words.append(w)
    return stop_words    
        
path = "stop_words.txt"
download_stopwords(path)
stop_words = create_stopwords(path)
print(stop_words)

File already exists.
['あそこ', 'あたり', 'あちら', 'あっち', 'あと', 'あな', 'あなた', 'あれ', 'いくつ', 'いつ', 'いま', 'いや', 'いろいろ', 'うち', 'おおまか', 'おまえ', 'おれ', 'がい', 'かく', 'かたち', 'かやの', 'から', 'がら', 'きた', 'くせ', 'ここ', 'こっち', 'こと', 'ごと', 'こちら', 'ごっちゃ', 'これ', 'これら', 'ごろ', 'さまざま', 'さらい', 'さん', 'しかた', 'しよう', 'すか', 'ずつ', 'すね', 'すべて', 'ぜんぶ', 'そう', 'そこ', 'そちら', 'そっち', 'そで', 'それ', 'それぞれ', 'それなり', 'たくさん', 'たち', 'たび', 'ため', 'だめ', 'ちゃ', 'ちゃん', 'てん', 'とおり', 'とき', 'どこ', 'どこか', 'ところ', 'どちら', 'どっか', 'どっち', 'どれ', 'なか', 'なかば', 'なに', 'など', 'なん', 'はじめ', 'はず', 'はるか', 'ひと', 'ひとつ', 'ふく', 'ぶり', 'べつ', 'へん', 'ぺん', 'ほう', 'ほか', 'まさ', 'まし', 'まとも', 'まま', 'みたい', 'みつ', 'みなさん', 'みんな', 'もと', 'もの', 'もん', 'やつ', 'よう', 'よそ', 'わけ', 'わたし', 'ハイ', '上', '中', '下', '字', '年', '月', '日', '時', '分', '秒', '週', '火', '水', '木', '金', '土', '国', '都', '道', '府', '県', '市', '区', '町', '村', '各', '第', '方', '何', '的', '度', '文', '者', '性', '体', '人', '他', '今', '部', '課', '係', '外', '類', '達', '気', '室', '口', '誰', '用', '界', '会', '首', '男', '女', '別', '話', '私', '屋', '店', '家', '場', '等', 

In [31]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b')
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
feature_sparse
features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [3, 2, 0, ..., 0, 0, 0],
       [2, 2, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [32]:
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(622,) が単語数
(622,)
[  0 475 255  62  81   5 436 131 428 524 427 379  82 404 288 337  86 121
 526 306]
0
0 75
ｱｯﾌﾟﾙ 43
情報 26
あっぷる 24
し 21
apple 16
車 12
会社 11
買取 11
ｻｰﾋﾞｽ 10
販売 10
秋田 10
する 9
製品 9
日本 8
無料 8
でき 7
介護 7
ｻｲﾄ 6
査定 6
企業 6
届け 6
株式 6
人気 6
ｸﾞﾙｰﾌﾟ 5
a 5
国内 5
青森 5
予約 5
ﾎﾃﾙ 5
さ 5
最大 5
店舗 5
ﾗﾝｷﾝｸﾞ 5
実績 5
ある 4
い 4
温泉 4
ｱﾒﾘｶ 4
開発 4
自動 4
限定 4
分かり 4
価格 4
ﾃﾞｼﾞﾀﾙ 4
いる 4
相場 4
得 4
ﾚﾝｽﾞ 4
ﾖﾄﾞﾊﾞｼ 4
最新 4
ﾌｫﾝ 4
詳細 3
端末 3
ｹｱ 3
食べ 3
ﾀﾙﾄ 3
ﾀﾌﾞﾚｯﾄ 3
料金 3
社員 3
紹介 3
通販 3
ﾎﾟｲﾝﾄ 3
充実 3
探す 3
美人 3
公式 3
翌日 3
ｺﾝﾀｸﾄ 3
英 3
取得 3
ﾘﾝｺﾞ 3
株価 3
団体 3
比較 3
りんご 3
ﾏﾝｼｮﾝ 3
満載 3
iphone 3
ﾆｭｰｽ 3
中古 3
会話 3
発表 3
購入 3
ios 3
ﾚﾋﾞｭｰ 3
商品 3
nhk 3
関連 3
ください 3
発信 3
開始 3
料理 2
居酒屋 2
賃貸 2
件 2
仲介 2
機能 2
展開 2
代行 2
教室 2
州 2
掲載 2
人物 2
新着 2
引越 2
配達 2
引越し 2
感染 2
関する 2
中心 2
電化 2
指定 2
全て 2
体操 2
安心 2
知る 2
即日 2
盛り 2
口ｺﾐ 2
合衆 2
番組 2
画像 2
申請 2
問い合わせ 2
国籍 2
在庫 2
満足 2
検討 2
津軽 2
気象 2
票 2
出演 2
作成 2
処 2
保険 2
個別 2
宿 2
元気 2
家庭 2
本社 2
大阪 2
全品 2
東京 2
英語 2
実施 2
架空 2
全国 2
美容 2
共 2
一覧 2
仙台 2
ﾁｬｰﾄ 2
pencil 2
ﾁﾗｼ 2
ﾁｪｯｸ 2
ﾀｳﾝ 2
q 2
ｿﾌﾄｳｪｱ 2
ｾﾝﾀｰ 2
ｽﾍﾟｯｸ 2
ｽｸｰ

In [33]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(norm='l2', sublinear_tf=True)
tfidf = tfidf_transformer.fit_transform(feature_sparse)
tfidf

<54x622 sparse matrix of type '<class 'numpy.float64'>'
	with 1029 stored elements in Compressed Sparse Row format>

In [34]:
features = np.array(tfidf.todense())
feature_sparse
features
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(622,) が単語数
(622,)
[  0 475 255  62  81   5 376 428 436 524  86 131 404 427  24 337  82 139
 306 379]
0
0 5.809838662418734
ｱｯﾌﾟﾙ 3.177626390521401
情報 2.6413487360948404
あっぷる 2.2760503024091006
し 2.057756428040795
apple 2.01468981343838
票 1.8320682956664422
買取 1.7807695248679598
車 1.7236475764664705
ｻｰﾋﾞｽ 1.6112259691014166
でき 1.6028542833309523
会社 1.4020961827040745
製品 1.374895617037018
販売 1.358691416560464
ios 1.3333377866519802
無料 1.2552163615721228
する 1.2138799261248385
価格 1.2033466911668687
査定 1.1959065809261262
秋田 1.1510568461984798
日本 1.1365338123065065
企業 1.091352925926134
すれ 1.0758067499415287
最大 1.0007168436933862
介護 0.9998486112740186
株式 0.9996594343734764
さ 0.9733452165740043
人気 0.9722860407982507
ｸﾞﾙｰﾌﾟ 0.9720401620650972
ｻｲﾄ 0.9561068759323732
国内 0.9531289394733906
実績 0.9404794699794281
ﾗﾝｷﾝｸﾞ 0.9127972837690347
分かり 0.8939618971850424
自動 0.8939618971850424
相場 0.8939618971850424
届け 0.8727679755112097
店舗 0.8698514161509366
い 0.7530325504898712
a 0.7412653156500957
最新 0.7258

In [35]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b', max_df=50, min_df=3)
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(68,) が単語数
(68,)
[ 0 55 26  4 10  2 49 47 15 59 46 44 11 29 37 12 14 23 13 32]
0
0 75
ｱｯﾌﾟﾙ 43
情報 26
あっぷる 24
し 21
apple 16
車 12
買取 11
会社 11
ｻｰﾋﾞｽ 10
販売 10
製品 9
する 9
日本 8
無料 8
でき 7
企業 6
届け 6
人気 6
査定 6
株式 6
ｻｲﾄ 6
ｸﾞﾙｰﾌﾟ 5
a 5
国内 5
実績 5
店舗 5
さ 5
青森 5
最大 5
ﾗﾝｷﾝｸﾞ 5
価格 4
分かり 4
得 4
ﾃﾞｼﾞﾀﾙ 4
ｱﾒﾘｶ 4
いる 4
温泉 4
い 4
開発 4
ある 4
相場 4
ﾌｫﾝ 4
自動 4
最新 4
ください 3
ﾆｭｰｽ 3
ﾀﾌﾞﾚｯﾄ 3
iphone 3
ﾎﾟｲﾝﾄ 3
ｹｱ 3
購入 3
充実 3
公式 3
取得 3
詳細 3
食べ 3
探す 3
料金 3
関連 3
比較 3
満載 3
発信 3
端末 3
美人 3
翌日 3
通販 3
ﾚﾋﾞｭｰ 3


In [158]:
np.sum(features,axis=1)

array([10,  1,  7, 16, 21, 10, 15, 20, 11, 17,  2,  1, 12, 13, 14, 14, 15,
       12, 14, 15,  1, 24, 15, 24, 16, 15,  7, 16, 13, 18,  1, 15, 19,  7,
       12, 22, 11,  6,  7,  3,  7, 12,  7,  1, 18,  8, 15, 15, 12,  1, 11,
        4,  7,  6, 10, 15, 15, 14, 22, 19, 18, 22, 14, 22, 13,  7,  7,  5,
        7, 15, 22, 22, 14, 22, 17, 15,  7, 10, 15,  8,  2, 14,  6,  6,  7,
        8,  4, 10,  1, 18,  4,  9,  9,  4, 11,  7, 17, 17])

どの文章も何かしらの特徴量はもっている．

In [161]:
print(features[1,:])
print(np.argmax(features[1,:]))
print(cv.get_feature_names()[np.argmax(features[1,:])])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
100
ｷｬｯｼｭ


In [162]:
np.sum(features,axis=0)[100]

5

In [186]:
cv.get_feature_names()

['0',
 'amazon',
 'fashion',
 'rakuten',
 'tv',
 'zozotown',
 'あり',
 'い',
 'いただけ',
 'いる',
 'おしゃれ',
 'ご覧',
 'し',
 'する',
 'でき',
 'できる',
 'まとめ',
 '一部',
 '中心',
 '交換',
 '人気',
 '代',
 '以外',
 '価格',
 '入荷',
 '公式',
 '出品',
 '即日',
 '取り扱う',
 '取り揃え',
 '取扱う',
 '古着',
 '品揃え',
 '商品',
 '圧倒',
 '多数',
 '大人',
 '女性',
 '安く',
 '安値',
 '定番',
 '小物',
 '届け',
 '幅広い',
 '幅広く',
 '店舗',
 '得',
 '情報',
 '手数',
 '掲載',
 '提供',
 '新作',
 '新品',
 '日本',
 '旧',
 '旬',
 '最大',
 '最新',
 '最短',
 '楽天',
 '洋服',
 '流行',
 '海外',
 '無料',
 '登場',
 '秋冬',
 '税込',
 '紹介',
 '美容',
 '翌日',
 '落札',
 '訳あり',
 '財布',
 '販売',
 '買い物',
 '購入',
 '返品',
 '送料',
 '通販',
 '配信',
 '配送',
 '開催',
 '除く',
 '雑貨',
 '類似',
 'ｱｰﾄ',
 'ｱｲﾃﾑ',
 'ｱｳﾀｰ',
 'ｱｳﾄﾚｯﾄ',
 'ｱﾍﾞﾆｭｰ',
 'ｱﾏｿﾞﾝ',
 'ｲﾍﾞﾝﾄ',
 'ｲﾝ',
 'ｲﾝﾅｰ',
 'ｳｪｱ',
 'ｵｰｸｼｮﾝ',
 'ｵｰﾙ',
 'ｵﾝ',
 'ｶｼﾞｭｱﾙ',
 'ｶﾃｺﾞﾘ',
 'ｷｬｯｼｭ',
 'ｷｯｽﾞ',
 'ｸｰﾎﾟﾝ',
 'ｺｰﾃﾞ',
 'ｺｰﾃﾞｨﾈｰﾄ',
 'ｺｰﾄ',
 'ｺｽﾒ',
 'ｺﾚｸｼｮﾝ',
 'ｻｲｽﾞ',
 'ｻｲﾄ',
 'ｼｭｰｽﾞ',
 'ｼｮｯﾋﾟﾝｸﾞ',
 'ｼｮｯﾌﾟ',
 'ｼﾞｬｹｯﾄ',
 'ｼﾞｭｴﾘｰ',
 'ｽｰﾂ',
 'ｽｳｪｯﾄ',
 'ｽｶｰﾄ',
 'ｽﾅｯﾌﾟ',
 'ｾｰﾙ',
 'ﾁｪｯｸ',
 'ﾄｯﾌﾟｽ',
 'ﾄﾚﾝﾄﾞ',
 'ﾄﾞﾚｽ',
 'ﾆｭ

In [187]:
df.site_name

0                    WEAR: ファッションコーディネート
2                     ファッション - Wikipedia
3            ファッションまとめ（レディース） - ZOZOTOWN
4                       ファッション通販ZOZOTOWN
5           ファッション通販SHOPLIST（ショップリスト ...
                     ...                
93    ファッション通販のhaco! | ハコ！毎日のお洋服と明日の ...
94              Fashion - ファッション - VOGUE
95     Amazonファッションタイムセール祭りでビジネスバッグが ...
96          Amazon ファッションタイムセール祭り - アマゾン
97            レディースファッション通販 Re:EDIT‐リエディ
Name: site_name, Length: 91, dtype: object