参考
https://hibiki-press.tech/python/mecab/5153

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import MeCab
import pandas as pd
import numpy as np
import re

In [1]:
keyword = 'ファッション'
# keyword = 'あっぷる'
filename = '../'+keyword+ '.csv'

In [27]:
df = pd.read_csv(filename)
df.head()
a = df[7:8]['target']
a.iloc[-1]

'人気 ｷｭﾚｰｼｮﾝﾒﾃﾞｨｱ 最新 ﾌｧｯｼｮﾝ 情報 ﾚﾃﾞｨｰｽ 集め 話題 ﾌｧｯｼｮﾝ ﾄﾚﾝﾄﾞ 情報 ご覧 いただけ ZOZOTOWN 0 ﾌﾞﾗﾝﾄﾞ'

https://www.delftstack.com/ja/howto/python-pandas/how-to-delete-dataframe-row-in-pandas-based-on-column-value/

In [26]:
cb1 = (df['snippet'] == 'キャッシュ' )
cb2 = (df['snippet'] == '類似ページ' )
condition_bool = (cb1 | cb2)
df.drop(df[ condition_bool == True ].index, inplace=True)
df[0:2]['target'].iloc[-1]

'人気 ﾌﾞﾗﾝﾄﾞ ｱｲﾃﾑ 入荷 ﾌｧｯｼｮﾝ ｳｫｰｶｰ 0 以上 人気 ﾌﾞﾗﾝﾄﾞ 公式 取り扱う ﾌｧｯｼｮﾝ 通販 ｻｲﾄ 即日 出荷 ｻｲｽﾞ 交換 返品 可 ｶﾃｺﾞﾘ 一覧 ﾛｸﾞ ｲﾝ ﾌﾞﾗﾝﾄﾞ 一覧 ｼｮｯﾋﾟﾝｸﾞ ｶｰﾄ'

In [8]:
def text_to_words(text):
    tagger = MeCab.Tagger("-O wakati")
    return tagger.parse(text).split()

In [65]:
texts = df['snippet'].tolist()
a = 0
for i in texts:
    if a < len(i):
        a = len(i)
a
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

174

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [50]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(652,) が単語数
(652,)
[370  82 463 452 244 115  23 247 363 516 234 207 430 320 319 378  62 261
 192 194]
370
ファッション 23
fashion 7
ワンピース 5
レディース 3
アート 3
online 3
30代 3
インテリア 3
バッグ 3
国立新美術館 3
アクセサリー 3
の公式通販サイト 3
メンズ 3
ストア 3
スカート 3
ファッションショー 2
buyma 2
カジュアル 2
で最短翌日お届け 2
ならお支払は2ヶ月後 2
キーホルダー 2
税込 2
インナー 2
bee 2
ポーチ 2
即日配送 2
キッズ 2
レディースファッション 2
blog 2
カルチャー 2
ビューティ 2
ボトムス 2
00 2
ファッション通販 2
ツケ払い 2
line 2
ジェネラル 2
アイダ 2
雑貨 2
から 2
アウター 2
2020 2
2021 2
一部地域 2
シャツ 2
島根県立石見美術館 2
大きいサイズ 2
アミューズメント 2
レディースファッション通販 2
サングラス 2
トップス 2
zozotownは8432ブランドのアイテムを公式に取扱うファッション通販サイトです 2
みんなの欲しいが見つかるお店です 1
の意味や使い方 1
の多彩なアイテムを紹介しているショッピング 1
は日本最大級のファッションコーディネートサイトです 1
は人気ブランドを取り扱うファッション通販サイトです 1
を便利なロケーションと快適な売場 1
をテーマに 1
ぽっちゃりさん向けのレディースファッションブランドre 1
わたしたちの毎日が 1
は人気ブランドや雑誌掲載アイテムを公式に取扱う国内最大級のファッション通販サイトです 1
の最新記事一覧です 1
の記事一覧ページです 1
の通販ならlohaco 1
の通販サイトです 1
ひっくり返して表面を揚げるときに 1
はやり 1
まだ生地が 1
もっと自由なファッションとスタイルで 1
のショッピングサイトです 1
の公式サイト 1
さらに輝く女性たちへ 1
ちょっとおしゃれな日常着をテーマに 1
たまプラーザ 1
そんなお洋服や雑貨 1
そして明日が 1
ずっと愛用したいアイテムなど 1
しかも気軽に

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(tokenizer=text_to_words, ngram_range=(1,2))
features_sparse = cv.fit_transform(texts)
features_sparse
features = np.array(features_sparse.todense())
print(features)

NameError: name 'text_to_words' is not defined

In [52]:

# print(cv.get_feature_names()[:])
# print(np.sum(features, axis=0))
# print(np.sum(features, axis=1))
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(652,) が単語数
(652,)
[370  82 463 452 244 115  23 247 363 516 234 207 430 320 319 378  62 261
 192 194]
370
ファッション 23
fashion 7
ワンピース 5
レディース 3
アート 3
online 3
30代 3
インテリア 3
バッグ 3
国立新美術館 3
アクセサリー 3
の公式通販サイト 3
メンズ 3
ストア 3
スカート 3
ファッションショー 2
buyma 2
カジュアル 2
で最短翌日お届け 2
ならお支払は2ヶ月後 2
キーホルダー 2
税込 2
インナー 2
bee 2
ポーチ 2
即日配送 2
キッズ 2
レディースファッション 2
blog 2
カルチャー 2
ビューティ 2
ボトムス 2
00 2
ファッション通販 2
ツケ払い 2
line 2
ジェネラル 2
アイダ 2
雑貨 2
から 2
アウター 2
2020 2
2021 2
一部地域 2
シャツ 2
島根県立石見美術館 2
大きいサイズ 2
アミューズメント 2
レディースファッション通販 2
サングラス 2
トップス 2
zozotownは8432ブランドのアイテムを公式に取扱うファッション通販サイトです 2
みんなの欲しいが見つかるお店です 1
の意味や使い方 1
の多彩なアイテムを紹介しているショッピング 1
は日本最大級のファッションコーディネートサイトです 1
は人気ブランドを取り扱うファッション通販サイトです 1
を便利なロケーションと快適な売場 1
をテーマに 1
ぽっちゃりさん向けのレディースファッションブランドre 1
わたしたちの毎日が 1
は人気ブランドや雑誌掲載アイテムを公式に取扱う国内最大級のファッション通販サイトです 1
の最新記事一覧です 1
の記事一覧ページです 1
の通販ならlohaco 1
の通販サイトです 1
ひっくり返して表面を揚げるときに 1
はやり 1
まだ生地が 1
もっと自由なファッションとスタイルで 1
のショッピングサイトです 1
の公式サイト 1
さらに輝く女性たちへ 1
ちょっとおしゃれな日常着をテーマに 1
たまプラーザ 1
そんなお洋服や雑貨 1
そして明日が 1
ずっと愛用したいアイテムなど 1
しかも気軽に

たぶんここから

In [56]:
texts = df['snippet']
# import re
# new_texts = [re.sub(r"[^a-zA-Z0-9]","",text) for text in texts] 
# new_texts

https://qiita.com/chamao/items/7edaba62b120a660657e
これみたら最強．ほぼこれ+max_dfの設定

In [57]:
import MeCab
def wakati(text):
    tagger = MeCab.Tagger('')
    tagger.parse('') 
    node = tagger.parseToNode(text)
    word_list = []
    while node:
        pos = node.feature.split(",")[0]
        if pos in ["名詞", "動詞", "形容詞"]:   # 対象とする品詞
            print(pos, node.surface)
            word = node.surface
            word_list.append(word)
        node = node.next
    return " ".join(word_list)

#例
# text = 'どれだけの天才でもどれだけの馬鹿でも自分一人だけの純粋な世界なんて存在しえないんだ。'
# print(wakati(text))  #=> どれ 天才 どれ 馬鹿 自分 一 人 純粋 世界 存在 し え ん

df["target"] = df[7:8]['snippet'].apply(wakati)
df["target"]

名詞 人気
名詞 キュレーションメディア
名詞 最新
名詞 ファッション
名詞 情報
名詞 レディース
動詞 集め
名詞 話題
名詞 ファッション
名詞 トレンド
名詞 情報
名詞 ご覧
動詞 いただけ
名詞 ZOZOTOWN
名詞 8430
名詞 ブランド


0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
     ... 
95    NaN
96    NaN
97    NaN
98    NaN
99    NaN
Name: target, Length: 100, dtype: object

In [58]:
import MeCab
def wakati(text):
    tagger = MeCab.Tagger('')
    tagger.parse('') 
    node = tagger.parseToNode(text)
    word_list = []
    while node:
        pos = node.feature.split(",")[0]
        print(pos, node.surface)
        word = node.surface
        word_list.append(word)
        node = node.next
    return " ".join(word_list)

#例
# text = 'どれだけの天才でもどれだけの馬鹿でも自分一人だけの純粋な世界なんて存在しえないんだ。'
# print(wakati(text))  #=> どれ 天才 どれ 馬鹿 自分 一 人 純粋 世界 存在 し え ん

df["target"] = df[7:8]['snippet'].apply(wakati)
df["target"]
wakati(df[7:8]['snippet'].iloc[-1])
# df[7:8]['snippet']

BOS/EOS 
名詞 人気
名詞 キュレーションメディア
助詞 の
名詞 最新
名詞 ファッション
名詞 情報
補助記号 （
名詞 レディース
補助記号 ）
助詞 を
動詞 集め
助動詞 まし
助動詞 た
補助記号 ！
接頭辞 今
名詞 話題
助詞 の
名詞 ファッション
助詞 や
名詞 トレンド
名詞 情報
助詞 を
名詞 ご覧
動詞 いただけ
助動詞 ます
補助記号 。
名詞 ZOZOTOWN
助詞 は
名詞 8430
名詞 ブランド
助詞 の
補助記号  
補助記号 .
補助記号 .
補助記号 .
BOS/EOS 
BOS/EOS 
名詞 人気
名詞 キュレーションメディア
助詞 の
名詞 最新
名詞 ファッション
名詞 情報
補助記号 （
名詞 レディース
補助記号 ）
助詞 を
動詞 集め
助動詞 まし
助動詞 た
補助記号 ！
接頭辞 今
名詞 話題
助詞 の
名詞 ファッション
助詞 や
名詞 トレンド
名詞 情報
助詞 を
名詞 ご覧
動詞 いただけ
助動詞 ます
補助記号 。
名詞 ZOZOTOWN
助詞 は
名詞 8430
名詞 ブランド
助詞 の
補助記号  
補助記号 .
補助記号 .
補助記号 .
BOS/EOS 


' 人気 キュレーションメディア の 最新 ファッション 情報 （ レディース ） を 集め まし た ！ 今 話題 の ファッション や トレンド 情報 を ご覧 いただけ ます 。 ZOZOTOWN は 8430 ブランド の \xa0 . . . '

In [59]:
df["target"]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
     ... 
95    NaN
96    NaN
97    NaN
98    NaN
99    NaN
Name: target, Length: 100, dtype: object

In [60]:
import mojimoji
df["target"] = df["target"].apply(mojimoji.zen_to_han)
df["target"]

TypeError: Argument 'text' has incorrect type (expected str, got float)

In [23]:
def normalize_number(text):
    # 連続した数字を0で置換
    replaced_text = re.sub(r'\d+', '0', text)
    return replaced_text

In [29]:
df["target"] = df["target"].apply(normalize_number)
df["target"].head()
df["target"]
# df["target"][57]

7                               Apple Music すれ 聴く こと でき
9     Apple Inc ｱｯﾌﾟﾙ ｶﾘﾌｫﾙﾆｱ 州 ｸﾊﾟﾁｰﾉ 本社 置く ｱﾒﾘｶ 合衆...
15    ｱｯﾌﾟﾙ ｱｯﾌﾟﾙ ｱﾒﾘｶ 企業 日本 おい 製品 ｻｰﾋﾞｽ 人気 集め い ﾃﾞｻ...
16    Apple ｱｯﾌﾟﾙ ｲﾝﾀｰﾈｯﾄ 関連 ﾃﾞｼﾞﾀﾙ 家庭 電化 ｿﾌﾄｳｪｱ 製品 ...
20                                   ﾍﾟｰｽ 新しい ｹﾞｰﾑ 追加 さ
29    日本 百科 全書 ﾆｯﾎﾟﾆｶ ｱｯﾌﾟﾙ 用語 解説 ｱﾒﾘｶ ｺﾝﾋﾟｭｰﾀ 会社 本社...
30    あっぷる 新着 情報 0 0 木 ささみ 豆もやし 香草 他 礒 永 由紀 先生 料理 ﾚｼ...
31        介護 保険 申請 代行 ｹｱ ﾌﾟﾗﾝ 作成 介護 ｻｰﾋﾞｽ 0 ｸﾞﾙｰﾌﾟ あっぷる
36    The latest Tweets from あっぷる ririka 0 apple PKA...
37    Apple ｱｯﾌﾟﾙ 製品 ｶﾃｺﾞﾘ 探す こと でき ｶﾃｺﾞﾘ 人気 売れ筋 製品 ...
38    株式 会社 あっぷる ｱｲﾋﾞｰ ｸﾞﾙｰﾌﾟ ｲﾀﾘｱﾝ ﾚｽﾄﾗﾝ ﾋﾟｯﾂｪﾘｱ 焼肉...
39    ｱｯﾌﾟﾙ 関する 記事 一覧 ﾍﾟｰｼﾞ GIZMODO JAPAN 最新 ﾌｫﾝ ﾃﾞｼ...
41    ｺﾝﾀｸﾄ ﾚﾝｽﾞ 通販 ﾚﾝｽﾞ ｱｯﾌﾟﾙ 安心 便利 ｺﾝﾀｸﾄ ﾚﾝｽﾞ ｵﾝ ﾗ...
42                                          すれ 観る こと でき
46    ｱｯﾌﾟﾙ 0 日本 時間 開発 ｲﾍﾞﾝﾄ WWDC 0 iOS 0 発表 し 今秋 提供...
47    介護 保険 申請 代行 ｹｱ ﾌﾟﾗﾝ 作成 介護 ｻｰﾋﾞｽ 0 ｸﾞﾙｰﾌﾟ あっぷる ...
48    ｱｯﾌﾟﾙ ﾊｳｼﾞﾝｸﾞ 福岡 新築 住宅 ﾘﾌｫｰﾑ ﾏﾝｼｮﾝ ﾘﾌｫｰﾑ 通し 人 ...
49    ｱｯﾌﾟﾙ apple 英語 ﾘﾝｺﾞ 林檎 こと 目次 0 会社 団体 0 0 架

In [30]:
import os
import urllib.request
def download_stopwords(path):
    url = 'http://svn.sourceforge.jp/svnroot/slothlib/CSharp/Version1/SlothLib/NLP/Filter/StopWord/word/Japanese.txt'
    if os.path.exists(path):
        print('File already exists.')
    else:
        print('Downloading...')
        # Download the file from `url` and save it locally under `file_name`:
        urllib.request.urlretrieve(url, path)
        
def create_stopwords(file_path):
    stop_words = []
    for w in open(path, "r"):
        w = w.replace('\n','')
        if len(w) > 0:
          stop_words.append(w)
    return stop_words    
        
path = "stop_words.txt"
download_stopwords(path)
stop_words = create_stopwords(path)
print(stop_words)

File already exists.
['あそこ', 'あたり', 'あちら', 'あっち', 'あと', 'あな', 'あなた', 'あれ', 'いくつ', 'いつ', 'いま', 'いや', 'いろいろ', 'うち', 'おおまか', 'おまえ', 'おれ', 'がい', 'かく', 'かたち', 'かやの', 'から', 'がら', 'きた', 'くせ', 'ここ', 'こっち', 'こと', 'ごと', 'こちら', 'ごっちゃ', 'これ', 'これら', 'ごろ', 'さまざま', 'さらい', 'さん', 'しかた', 'しよう', 'すか', 'ずつ', 'すね', 'すべて', 'ぜんぶ', 'そう', 'そこ', 'そちら', 'そっち', 'そで', 'それ', 'それぞれ', 'それなり', 'たくさん', 'たち', 'たび', 'ため', 'だめ', 'ちゃ', 'ちゃん', 'てん', 'とおり', 'とき', 'どこ', 'どこか', 'ところ', 'どちら', 'どっか', 'どっち', 'どれ', 'なか', 'なかば', 'なに', 'など', 'なん', 'はじめ', 'はず', 'はるか', 'ひと', 'ひとつ', 'ふく', 'ぶり', 'べつ', 'へん', 'ぺん', 'ほう', 'ほか', 'まさ', 'まし', 'まとも', 'まま', 'みたい', 'みつ', 'みなさん', 'みんな', 'もと', 'もの', 'もん', 'やつ', 'よう', 'よそ', 'わけ', 'わたし', 'ハイ', '上', '中', '下', '字', '年', '月', '日', '時', '分', '秒', '週', '火', '水', '木', '金', '土', '国', '都', '道', '府', '県', '市', '区', '町', '村', '各', '第', '方', '何', '的', '度', '文', '者', '性', '体', '人', '他', '今', '部', '課', '係', '外', '類', '達', '気', '室', '口', '誰', '用', '界', '会', '首', '男', '女', '別', '話', '私', '屋', '店', '家', '場', '等', 

In [31]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b')
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
feature_sparse
features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [3, 2, 0, ..., 0, 0, 0],
       [2, 2, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [32]:
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(622,) が単語数
(622,)
[  0 475 255  62  81   5 436 131 428 524 427 379  82 404 288 337  86 121
 526 306]
0
0 75
ｱｯﾌﾟﾙ 43
情報 26
あっぷる 24
し 21
apple 16
車 12
会社 11
買取 11
ｻｰﾋﾞｽ 10
販売 10
秋田 10
する 9
製品 9
日本 8
無料 8
でき 7
介護 7
ｻｲﾄ 6
査定 6
企業 6
届け 6
株式 6
人気 6
ｸﾞﾙｰﾌﾟ 5
a 5
国内 5
青森 5
予約 5
ﾎﾃﾙ 5
さ 5
最大 5
店舗 5
ﾗﾝｷﾝｸﾞ 5
実績 5
ある 4
い 4
温泉 4
ｱﾒﾘｶ 4
開発 4
自動 4
限定 4
分かり 4
価格 4
ﾃﾞｼﾞﾀﾙ 4
いる 4
相場 4
得 4
ﾚﾝｽﾞ 4
ﾖﾄﾞﾊﾞｼ 4
最新 4
ﾌｫﾝ 4
詳細 3
端末 3
ｹｱ 3
食べ 3
ﾀﾙﾄ 3
ﾀﾌﾞﾚｯﾄ 3
料金 3
社員 3
紹介 3
通販 3
ﾎﾟｲﾝﾄ 3
充実 3
探す 3
美人 3
公式 3
翌日 3
ｺﾝﾀｸﾄ 3
英 3
取得 3
ﾘﾝｺﾞ 3
株価 3
団体 3
比較 3
りんご 3
ﾏﾝｼｮﾝ 3
満載 3
iphone 3
ﾆｭｰｽ 3
中古 3
会話 3
発表 3
購入 3
ios 3
ﾚﾋﾞｭｰ 3
商品 3
nhk 3
関連 3
ください 3
発信 3
開始 3
料理 2
居酒屋 2
賃貸 2
件 2
仲介 2
機能 2
展開 2
代行 2
教室 2
州 2
掲載 2
人物 2
新着 2
引越 2
配達 2
引越し 2
感染 2
関する 2
中心 2
電化 2
指定 2
全て 2
体操 2
安心 2
知る 2
即日 2
盛り 2
口ｺﾐ 2
合衆 2
番組 2
画像 2
申請 2
問い合わせ 2
国籍 2
在庫 2
満足 2
検討 2
津軽 2
気象 2
票 2
出演 2
作成 2
処 2
保険 2
個別 2
宿 2
元気 2
家庭 2
本社 2
大阪 2
全品 2
東京 2
英語 2
実施 2
架空 2
全国 2
美容 2
共 2
一覧 2
仙台 2
ﾁｬｰﾄ 2
pencil 2
ﾁﾗｼ 2
ﾁｪｯｸ 2
ﾀｳﾝ 2
q 2
ｿﾌﾄｳｪｱ 2
ｾﾝﾀｰ 2
ｽﾍﾟｯｸ 2
ｽｸｰ

In [33]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer(norm='l2', sublinear_tf=True)
tfidf = tfidf_transformer.fit_transform(feature_sparse)
tfidf

<54x622 sparse matrix of type '<class 'numpy.float64'>'
	with 1029 stored elements in Compressed Sparse Row format>

In [34]:
features = np.array(tfidf.todense())
feature_sparse
features
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(622,) が単語数
(622,)
[  0 475 255  62  81   5 376 428 436 524  86 131 404 427  24 337  82 139
 306 379]
0
0 5.809838662418734
ｱｯﾌﾟﾙ 3.177626390521401
情報 2.6413487360948404
あっぷる 2.2760503024091006
し 2.057756428040795
apple 2.01468981343838
票 1.8320682956664422
買取 1.7807695248679598
車 1.7236475764664705
ｻｰﾋﾞｽ 1.6112259691014166
でき 1.6028542833309523
会社 1.4020961827040745
製品 1.374895617037018
販売 1.358691416560464
ios 1.3333377866519802
無料 1.2552163615721228
する 1.2138799261248385
価格 1.2033466911668687
査定 1.1959065809261262
秋田 1.1510568461984798
日本 1.1365338123065065
企業 1.091352925926134
すれ 1.0758067499415287
最大 1.0007168436933862
介護 0.9998486112740186
株式 0.9996594343734764
さ 0.9733452165740043
人気 0.9722860407982507
ｸﾞﾙｰﾌﾟ 0.9720401620650972
ｻｲﾄ 0.9561068759323732
国内 0.9531289394733906
実績 0.9404794699794281
ﾗﾝｷﾝｸﾞ 0.9127972837690347
分かり 0.8939618971850424
自動 0.8939618971850424
相場 0.8939618971850424
届け 0.8727679755112097
店舗 0.8698514161509366
い 0.7530325504898712
a 0.7412653156500957
最新 0.7258

In [35]:
cv = CountVectorizer(stop_words=stop_words, token_pattern=u'(?u)\\b\\w+\\b', max_df=50, min_df=3)
feature_sparse = cv.fit_transform(df["target"])
features = np.array(feature_sparse.todense())
print(np.sum(features, axis=0).shape,"が単語数")
print(np.argsort(np.sum(features, axis=0, keepdims=False)).shape)
A=np.argsort(np.sum(features, axis=0))[::-1]
print(A[0:20])
print(np.argmax(np.sum(features, axis=0)))
for i in A:
    print(cv.get_feature_names()[i], np.sum(features, axis=0)[i])

(68,) が単語数
(68,)
[ 0 55 26  4 10  2 49 47 15 59 46 44 11 29 37 12 14 23 13 32]
0
0 75
ｱｯﾌﾟﾙ 43
情報 26
あっぷる 24
し 21
apple 16
車 12
買取 11
会社 11
ｻｰﾋﾞｽ 10
販売 10
製品 9
する 9
日本 8
無料 8
でき 7
企業 6
届け 6
人気 6
査定 6
株式 6
ｻｲﾄ 6
ｸﾞﾙｰﾌﾟ 5
a 5
国内 5
実績 5
店舗 5
さ 5
青森 5
最大 5
ﾗﾝｷﾝｸﾞ 5
価格 4
分かり 4
得 4
ﾃﾞｼﾞﾀﾙ 4
ｱﾒﾘｶ 4
いる 4
温泉 4
い 4
開発 4
ある 4
相場 4
ﾌｫﾝ 4
自動 4
最新 4
ください 3
ﾆｭｰｽ 3
ﾀﾌﾞﾚｯﾄ 3
iphone 3
ﾎﾟｲﾝﾄ 3
ｹｱ 3
購入 3
充実 3
公式 3
取得 3
詳細 3
食べ 3
探す 3
料金 3
関連 3
比較 3
満載 3
発信 3
端末 3
美人 3
翌日 3
通販 3
ﾚﾋﾞｭｰ 3


In [158]:
np.sum(features,axis=1)

array([10,  1,  7, 16, 21, 10, 15, 20, 11, 17,  2,  1, 12, 13, 14, 14, 15,
       12, 14, 15,  1, 24, 15, 24, 16, 15,  7, 16, 13, 18,  1, 15, 19,  7,
       12, 22, 11,  6,  7,  3,  7, 12,  7,  1, 18,  8, 15, 15, 12,  1, 11,
        4,  7,  6, 10, 15, 15, 14, 22, 19, 18, 22, 14, 22, 13,  7,  7,  5,
        7, 15, 22, 22, 14, 22, 17, 15,  7, 10, 15,  8,  2, 14,  6,  6,  7,
        8,  4, 10,  1, 18,  4,  9,  9,  4, 11,  7, 17, 17])

どの文章も何かしらの特徴量はもっている．

In [161]:
print(features[1,:])
print(np.argmax(features[1,:]))
print(cv.get_feature_names()[np.argmax(features[1,:])])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
100
ｷｬｯｼｭ


In [162]:
np.sum(features,axis=0)[100]

5

In [186]:
cv.get_feature_names()

['0',
 'amazon',
 'fashion',
 'rakuten',
 'tv',
 'zozotown',
 'あり',
 'い',
 'いただけ',
 'いる',
 'おしゃれ',
 'ご覧',
 'し',
 'する',
 'でき',
 'できる',
 'まとめ',
 '一部',
 '中心',
 '交換',
 '人気',
 '代',
 '以外',
 '価格',
 '入荷',
 '公式',
 '出品',
 '即日',
 '取り扱う',
 '取り揃え',
 '取扱う',
 '古着',
 '品揃え',
 '商品',
 '圧倒',
 '多数',
 '大人',
 '女性',
 '安く',
 '安値',
 '定番',
 '小物',
 '届け',
 '幅広い',
 '幅広く',
 '店舗',
 '得',
 '情報',
 '手数',
 '掲載',
 '提供',
 '新作',
 '新品',
 '日本',
 '旧',
 '旬',
 '最大',
 '最新',
 '最短',
 '楽天',
 '洋服',
 '流行',
 '海外',
 '無料',
 '登場',
 '秋冬',
 '税込',
 '紹介',
 '美容',
 '翌日',
 '落札',
 '訳あり',
 '財布',
 '販売',
 '買い物',
 '購入',
 '返品',
 '送料',
 '通販',
 '配信',
 '配送',
 '開催',
 '除く',
 '雑貨',
 '類似',
 'ｱｰﾄ',
 'ｱｲﾃﾑ',
 'ｱｳﾀｰ',
 'ｱｳﾄﾚｯﾄ',
 'ｱﾍﾞﾆｭｰ',
 'ｱﾏｿﾞﾝ',
 'ｲﾍﾞﾝﾄ',
 'ｲﾝ',
 'ｲﾝﾅｰ',
 'ｳｪｱ',
 'ｵｰｸｼｮﾝ',
 'ｵｰﾙ',
 'ｵﾝ',
 'ｶｼﾞｭｱﾙ',
 'ｶﾃｺﾞﾘ',
 'ｷｬｯｼｭ',
 'ｷｯｽﾞ',
 'ｸｰﾎﾟﾝ',
 'ｺｰﾃﾞ',
 'ｺｰﾃﾞｨﾈｰﾄ',
 'ｺｰﾄ',
 'ｺｽﾒ',
 'ｺﾚｸｼｮﾝ',
 'ｻｲｽﾞ',
 'ｻｲﾄ',
 'ｼｭｰｽﾞ',
 'ｼｮｯﾋﾟﾝｸﾞ',
 'ｼｮｯﾌﾟ',
 'ｼﾞｬｹｯﾄ',
 'ｼﾞｭｴﾘｰ',
 'ｽｰﾂ',
 'ｽｳｪｯﾄ',
 'ｽｶｰﾄ',
 'ｽﾅｯﾌﾟ',
 'ｾｰﾙ',
 'ﾁｪｯｸ',
 'ﾄｯﾌﾟｽ',
 'ﾄﾚﾝﾄﾞ',
 'ﾄﾞﾚｽ',
 'ﾆｭ

In [187]:
df.site_name

0                    WEAR: ファッションコーディネート
2                     ファッション - Wikipedia
3            ファッションまとめ（レディース） - ZOZOTOWN
4                       ファッション通販ZOZOTOWN
5           ファッション通販SHOPLIST（ショップリスト ...
                     ...                
93    ファッション通販のhaco! | ハコ！毎日のお洋服と明日の ...
94              Fashion - ファッション - VOGUE
95     Amazonファッションタイムセール祭りでビジネスバッグが ...
96          Amazon ファッションタイムセール祭り - アマゾン
97            レディースファッション通販 Re:EDIT‐リエディ
Name: site_name, Length: 91, dtype: object